Gruntfile.js
src/export.js
test/globals-node.js
test/globals.js

Ref #521
More info: https://github.com/jquery/qunit/issues/521#issuecomment-65656852
Basically, we want to ensure that `require('qunitjs').QUnit` works in all CommonJS environments, even if it is achieved by `QUnit.QUnit = QUnit`. Node.js was the only outlier at this point.
Also added and updated a few related tests.

Build: Support Node.js export parity with CommonJS

---

reporter/html.js

Also, fixed regression from `1.15.0` for adding a link to #qunit-header.
Fixes #716

HTML Reporter: Fix regression for old markup

---

.travis.yml
package.json

This runs our unit tests on all supported browsers for all commits, including pull requests, using the existing `browserstack-runner` configuration. A [sample run](https://travis-ci.org/jzaefferer/qunit/builds/45673762) took 2 1/2 minutes to test on 14 browsers.
This works, but I expect that we'll get the occasional failure, likely with one or more workers timing out, [like this](https://travis-ci.org/jzaefferer/qunit/builds/45670237). I think thats an acceptable tradeoff. We'll continue working with BrowserStack to make testing more reliable.
As for the obscured credentials: Those are easy enough to decode, the point is to avoid them being searchable, that is a search for "browserstack" on GitHub won't immediately show these credentials. This is a temporary solution until Travis CI …

Build: Enable PR testing with browserstack-runner

---

reporter/html.js

Without any module at the test suite, the Reporter doesn't create
the select tag to filter the modules. The test filter was trying
to get the selected value to set the filter in order to keep it
at the url parameters.
Closes #748

HTML Reporter: Fix test filter without any module

---

src/assert.js
test/globals.js

Fixes regression found at #752 and add tests for exported throws assertions.

Assert: Fix missing test on exported throws

---

src/assert.js
test/assert.js

Also test failed assertions by mocking `QUnit.assert.push`
These changes were also good to fix assert.throws behaviour.
The other way to test failing assertions I have in mind is reported at #765, but I believe this is the best way to go.
Ref #765 (which might be closed after landing this patch).

Tests: Add missing tests for assertions

---

browserstack.json
src/core.js

Ref #758 
I did a test on every supported browser and so far we can drop the `e.stacktrace` part and simplify the way we get the stack information.
The try catch blocks are necessary for IE10 and IE11, otherwise, we could get rid of them.

Core: Simplify stack trace methods

---

browserstack.json
test/autostart.html
test/autostart.js

Also remove the QUnit.load as they were invalid.
Closes #798
Closes #803

Tests: Avoid loosen errors on autostart test

---

README.md
package.json

Replace badge from jenkins.jquery.org with badge from Travis CI
Follows-up d1564e1a47 and pull #849, which remove TestSwarm from the Jenkins run.
However that means the primary badge isn't very useful anymore and doesn't
include cross-browser results. It also seems that the Jenkins badge plugin doesn't
handle proxy caching properly, causing it to show as "Unstable" on GitHub long
after the build was fixed.
Update both badges to use SVG so that it doesn't look pixelated on high density screens.

Readme: Replace Jenkins badge with Travis

---

src/core/utilities.js
src/equiv.js
test/main/deepEqual.js

Also adds an extra code golf (with step-by-step commits) based on coverage.
As mentioned on 5e4ba82, `QUnit.objectType` already covers all JS types except the new comming Symbol on ES2015. For other object types it will return `'object'` which is covered too.

Core: Support Symbol types on QUnit.equiv

---

build/browserstack-legacy-1.json
build/browserstack-legacy-2.json

Removing IE 6, 7, and 8, Safari 5.1 and 6.
@mgol, I want to sync this up with jQuery Core while QUnit is still on 1.x.

Remove browserstack runs on legacy browsers

---

.travis.yml
README.md
package.json

Removes need for custom code in .travis.yml, and makes it so that
`npm install && npm test` works out of the box without requiring
grunt-cli pre-installed.
This works because npm always makes exported bin commands available via the local `node_modules/.bin` directory in the environment PATH as used by of npm commands.

Build: Add grunt-cli to devDependencies

---

reporter/html.js
src/qunit.css

Fixes gh-988
Ref 0780127
Updates styles, enlarges interaction targets (i.e., `display:block`), adds a down-arrow and Reset/Apply buttons in the module picker, displays current module section (comma-separated) in placeholder and tooltip text, and closes the drop-down on Escape keydown. Possible more as well, but those are the key changes.

HTML Reporter: Improve toolbar styles & accessibility

---

src/dump.js
test/main/deepEqual.js
test/main/dump.js

Addressing #1008. The root issue is that `dump.parse` didn't have a parser defined for object's of type `symbol` and thus it didn't return a `string`. This fixes that and adds a test to catch regressions.
Here are some examples of the fix in action. The first test is essentially `Symbol("QUnit") === Symbol("QUnit")` and the test shows `Symbol("QUnit1") === Symbol("QUnit2")`.

Dump: Add parser for Symbol

---

src/test.js
test/logs.js

Addressing #1004.
This ensures that the `runtime` property during `testDone` logging for skipped tests is alway `0`. I think a future state where we remove the property all together is possible, but since that would be a breaking change I am not inclined to do that at this point in time.
cc @flore77 @jzaefferer @leobalter

Core: Ensure runtime for skipped tests is 0

---

package.json
rollup.config.js

This is should fix the build by removing our dependency on the es2015-rollup preset.

Build: Remove dependency on es2015-rollup preset

---

bower.json

Bower has adopted SPDX format license names, like npm's package.json.
Having a url here confuses some automated tools :).
https://github.com/bower/bower/issues/895
Thanks!

change bower.json license to SPDX format

---

src/core.js
src/core/config.js
src/test.js
test/callbacks.js

Addressing #1044. This ensures that `moduleDone` and `moduleStart` are fired exactly once per module.
Also, removes `config.previousModule` and `config.moduleStats`, these aren't documented anywhere and seem to have just been there to pass information around QUnit internals, so it seems beneficial to get them off the global. @leobalter hope you can verify if it is safe to remove these.
A couple additional things noticed in this cleanup:
* Modules currently have a `childModule` property, this contains a reference to a single module. This likely means that modules with multiple nested children are broken. We should fix that.
* `moduleDone` reports the `runtime` of the module, but this is done by taking a "start" value when `moduleStart` is emitted. This is likely to produce odd and not very …

Core: Improve moduleDone and moduleStart behavior

---

package.json
test/.eslintrc.json
test/deprecated.js
test/stack-errors.js

As some folks know, I maintain the [eslint-plugin-qunit](https://github.com/platinumazure/eslint-plugin-qunit) ESLint plugin. The purpose of that plugin is to provide QUnit-specific rules for ESLint.
I haven't had a good open-source project to dogfood the plugin, so now that we're using ESLint, I'd like to offer it to this project.
This PR enables all of the rules in the ["two" configuration](https://github.com/platinumazure/eslint-plugin-qunit#two) (i.e., rules related to proper use of QUnit 2.0 APIs). If there is interest and we want to use more rules from the project, that could be done in a separate PR.

Build: Consume eslint-plugin-qunit, use "two" configuration

---

src/core.js
src/core/config.js
src/test.js
test/callbacks.js

As discussed in #1047:
> Modules currently have a childModule property, this contains a reference to a single module. This likely means that modules with multiple nested children are broken. We should fix that.

Core: Support multiple nested modules hooks properly

---

reporter/html.js

Looks like QUnit.config.collapse = false stopped working with commit 5333de89dda55691e1634081e6fe97033185f836. This fixes that regression.

HTML Reporter: Fix expanding failed tests when collapse is false.

---

.travis.yml
package.json

Includes our supported versions in package.json to clarify the current support.
This also brings our support policy in line with Rollup, so we can avoid having to switch versions for building.
Fixes #1067

Build: Update Node support versions

---

Gruntfile.js
src/core/config.js
src/export.js
test/preconfigured.html
test/preconfigured.js

If a global QUnit.config object is present before QUnit is loaded,
the default config values will be extended.
The use case is to configure QUnit before it is loaded.
Closes #1059

Core: Support a predefined QUnit.config

---

build/tasks/test-on-node.js
src/core.js

Only in non-browser environments, avoiding breaking changes.
Closes gh-1081

QUnit.load is now called inside QUnit.start

---

src/assert.js

Closes #986 (I think).
I couldn't seem to find any code for `QUnit.push`, but did find code for `assert.push` (which is also deprecated).

Assert: Deprecate assert.push

---

reporter/html.js
reporter/reporter.js

> 80a14ee5ac49c7f0981884a6cbb5786dea3a9c8b implemented Rollup.
> Reporter is importing `html` before `urlparams`, but `urlparams` needs
> to be loaded before `html` as it was in the previous commit.
> 
> Tried reordering the imports within the file, but running the build task
> seemed to not change the output. By moving the `urlparams` import
> into `html`, the built output is correct.
> 
> Fixes #1082 
Does anyone know why reordering the imports in https://github.com/qunitjs/qunit/blob/master/reporter/reporter.js doesn't have the desired effect?

Reporter: move urlparams import from reporter to html

---

src/assert.js

Potentially unneeded, but as we move forward and start introducing new features (such as Step assertions, Todo tests, new reporters, etc.), it'd be nice for the codebase to be modernized and cleaned up. I personally find this helps lower the barrier to entry for new contributors if the codebase is easy to read.
A couple things to discuss:
1. Do we need to do refactoring separately (like this PR) or should we let it happen over time? I tend to think letting it happen over time will tend towards it not happening at all.
2. Is there an ES6 style guide for jQuery? If not, we should define eslint rules for things like `let` vs `const` as they come up.

Assert: ES6 Refactor

---

src/assert.js
src/logger.js

As brought up in https://github.com/qunitjs/qunit/pull/1093, this adds a `Logger` singleton to handle proxying to `console` methods to abstract potential logic branches.
Unsure how useful it will be in the long run, but for now it makes for simpler code (especially as we plan to deprecate things (e.g., `assert.push`, `QUnit.load`)

Core: Add logger singleton to handle messages

---

Gruntfile.js
src/assert.js
src/test.js
test/index.html
test/main/assert/step.js

As discussed in #1075. Relevant commit messages:
> Introduces the assert.step function which logs a passing assertion
> for steps in a test. These steps are stored as string values to
> help verify order of operations.
> Introduces the assert.verifySteps function to complement assert.step.
> This acceptances an array of string values to compare to the steps
> that have executed for the current test.

Assert: Add step and verifySteps functions

---

src/assert.js
test/main/assert/step.js

As brought up in https://github.com/qunitjs/qunit/pull/1094#discussion_r97558254. When calling `assert.verifySteps()` after a failed `assert.step()`, the bad values will be used in the comparison, even though `You must provide a message to assert.step` is the logged message.

Assert: Use actual values for verifySteps on failed steps

---

build/tasks/test-on-node.js
package.json
reporter/html.js
src/core.js
src/qunit.css
src/test.js
test/logs.js
yarn.lock

Supersedes #1006.
This takes a simpler approach to implementing `QUnit.todo`. We simply add a `todo` flag to `log` and `testDone` details that denotes if an assertion or a test was part of a `todo`. The reporter can then handle that scenario appropriately.
This approach keeps QUnit's internal logic simple and encourages reporters to report success/failure for a test suite based on the outcome of tests and _not_ on the outcome of assertions, which is inline with the thinking of js-reporters.
While this likely means most reporters will have to implement new logic to support `todo`, this change should not break existing reporters and provides a relatively clear path to supporting the new feature.
_Note: Assuming this implementation looks okay, I will open a PR to support `todo` in …

Core: Implement QUnit.todo

---

src/equiv.js
test/main/deepEqual.js

Also:
- Redefine Map/Set equivalence to match the .has methods
- Fix recursion bugs, and add tests for failing cases
- Implement recursion for Map
- Document algorithm and rationale

Core: Rewrite QUnit.equiv to be breadth-first

---

src/core.js

Fixes #1102.
Note: Unsure how we can test this since the issue manifests itself as `done` being triggered twice which our reporter exits after the first `done` call.

Core: Fix double begin when calling start in Node

---

src/core.js
src/reports/suite.js
src/reports/test.js
src/test.js
test/events.js

~~**Note: Still a work-in-progress, likely will not be ready to review until after https://github.com/qunitjs/qunit/pull/1080 has landed.**~~
Since all the suite and test events are intertwined in the js-reporter spec, we have to introduce the remaining events all at once.
This also adds a `todo` field to the `assertion` event data now that `QUnit.todo()` has landed.
---
After this PR, we should update the HTML reporter to use the new event emitter interface, introduce a generic TAP reporter, and then hopefully iterate on our existing test-on-node task to become the foundation for a CLI.

Core: Add remaining js-reporter events

---

src/core.js

When I submitted https://github.com/qunitjs/qunit/pull/1103, it turns out the test-on-node task never actually ran. The reason is that we don't set `autostart` to `true`. This fix will handle that case as well.

Core: Fix start on Node when autostart is not set to true

---

.eslintrc.json

Enabling nine fairly simple ES2015 ESLint rules for the repo, none of which required any code changes.
* [arrow-spacing](http://eslint.org/docs/rules/arrow-spacing): Assuming arrow operators should always have spaces around them
* [constructor-super](http://eslint.org/docs/rules/constructor-super): In a derived class with a constructor, ensure `super()` is called right away
* [no-const-assign](http://eslint.org/docs/rules/no-const-assign): Forbid reassigning a const variable (would throw runtime error)
* [no-dupe-class-members](http://eslint.org/docs/rules/no-dupe-class-members): Class members must be unique (otherwise latter definition would override former)
* [no-duplicate-imports](http://eslint.org/docs/rules/no-duplicate-imports): Multiple imports from same module are not allowed, …

All: Enable some ES2015-specific ESLint rules

---

test/index.html

Just adding the onError tests to the main browser page.
@gibson042 I ran the tests on Chrome and Firefox (both in isolation and via test/index.html) and I don't see any issues. This is based off current master, so #1108 is not included here. Just want to confirm you only were seeing the issue in #1108? Or is there something I need to do differently to reproduce the issue on master?

Tests: Ensure onError tests are included in test/index.html

---

Gruntfile.js
src/core/config.js
src/globals.js
test/reorder.html
test/reorder.js

Continuing https://github.com/qunitjs/qunit/pull/1112. GitHub wouldn't allow me to push to that PR since I modified the history.
> Prior to this PR `const sessionStorage` shadowed the global `sessionStorage`.
> This resulted in the feature sniffing function to always fail, as `sessionStorage` would always be `undefined`
cc @stefanpenner

Core: Fix sessionStorage feature detection

---

.eslintrc.json
reporter/html.js
src/assert.js
src/events.js
src/reports/suite.js
src/reports/test.js
src/test.js

Flags `let` variables that don't ever get reassigned and could be turned into `const` variables. Does not flag `var` variables.
See [here](http://eslint.org/docs/rules/prefer-const) for more information.

All: Enable ESLint prefer-const rule

---

README.md
RELEASE.md

After doing the last couple releases, I felt we really needed some better documentation around how to do a release for maintainers, so I pulled together most of what I know into a `RELEASE.md` file.
One particular thing to note is that in doing this, I forked [jquery-release](https://github.com/jquery/jquery-release) to the [qunitjs org](https://github.com/qunitjs/jquery-release) to avoid individual maintainers from having to modify it when doing a release. We can move off this whenever we get around to revamping the release script (in other words, whenever we address https://github.com/qunitjs/qunit/issues/1073).
Also, @leobalter when you have a chance can you email me the Twitter account info? We haven't announced the last several releases, so it would be good to start doing that again.

Readme: Add detailed release instructions

---

src/core.js
src/core/processing-queue.js
src/core/utilities.js
src/test.js

Currently, the logic for processing the queue of tests is scattered. This pulls the two core pieces into a new construct `ProcessingQueue` with an interface that more clearly communicates what `process` and `synchronize` used to do.
In other words:
- `process()` -> `ProcessingQueue.advance()`: Moves the queue forward
- `synchronize()` -> `ProcessingQueue.add()`: Adds a function to the queue
This is being done preemptively to support the "watch" feature in the forthcoming CLI. We'll need to refactor a portion of how the queue is processed in order to properly abort test runs when watched files change.

Core: Introduce ProcessingQueue in internals

---

bin/qunit
bin/run.js
src/reports/suite.js
src/reports/test.js
src/test.js
test/cli/main.js

This PR does two things:
1. Introduces a `--filter` option to the CLI for setting `QUnit.config.filter`
2. Fixes a bug in the new event emitter interface, where filtered tests were still being counted even when not run

CLI: Support filtering tests

---

bin/qunit
bin/run.js
test/cli/fixtures/expected/tap-outputs.js
test/cli/main.js

This adds support to the CLI for `QUnit.config.seed`. Behaves similarly to the browser query param.

CLI: Add seed option

---

bin/qunit

This provides some helpful, descriptive text when using `qunit --help`:
```bash
$ qunit --help
Usage: qunit [options] [files]
Runs tests using the QUnit framework.
Files should be a space-separated list of file/directory paths and/or glob
expressions. Defaults to 'test/**/*.js'.
For more info on working with QUnit, checkout http://qunitjs.com.
```
Meant to have this in the original PR, but forgot.

CLI: Add description to help command

---

src/core.js
src/core/config.js
src/core/processing-queue.js
src/test.js

_Note: This is a follow up to https://github.com/qunitjs/qunit/pull/1121_.
Bear with me a moment, while I explain what this PR is doing. In the **current** system, when you add a test, it is [queued up as a single function](https://github.com/qunitjs/qunit/blob/41cb62569786de4b0d64c48cd0bf099839e28ae4/src/test.js#L314-L345), named `run`. Thus, when a test suite begins running, the queue generally looks something like this (not real code, just for illustration purposes):
```bash
QUnit.config.queue = [
function run(),
function run(),
];
```
When we begin processing the queue, each of those individual `run` functions is replaced by [a series of sub-functions](https://github.com/qunitjs/qunit/blob/41cb62569786de4b0d64c48cd0bf099839e28ae4/src/test.js#L317-L344). These functions, however, wind …

Core: Revamp processing order to enable proper aborting of test runs

---

.travis.yml
bin/qunit
bin/run.js
package.json
src/test.js
test/cli/fixtures/expected/watch-tap-outputs.js
test/cli/watch.js
yarn.lock

This PR introduces a `--watch` option to the CLI so that tests will re-run when a file is added, changed, or removed from the working directory. It also ensures that if one of the above occurs while tests are executing, then the current test finishes and does any cleanup (via `after`/`afterEach` hooks) before restarting.
This depends on https://github.com/qunitjs/qunit/pull/1121 and https://github.com/qunitjs/qunit/pull/1124. I recommend not reviewing until both of those PRs are merged, because this PR will be much simpler afterward.
Todo:

CLI: Add file watching option

---

src/test.js
test/onerror/outside-test.js

Fix endless recursive loop between Test#pushFailure and
Assert#pushResult.
See #1119 for details
Let me know if anything more is needed for this PR.

Core: Test#pushFailure now calls Test#pushResult

---

src/test.js
test/main/assert.js

Based on discussion in https://github.com/qunitjs/qunit/issues/1145#issuecomment-292290443, I investigated if we properly erred when asserting outside the active test, and it turns out we do not. This fixes that and adds a test.
There's a potential that this could break some currently passing test suites, but I would consider those bugs as it poor testing practice to have assertions take place outside the actual test they're associated with.

Core: Ensure assertions occur while test is running

---

docs/assert/async.md
src/assert.js
src/core/processing-queue.js
src/test.js
test/main/async.js

~~Implements the feature discussed in https://github.com/qunitjs/qunit/issues/1145.~~
Allow assertions after the `assert.async()` callback is invoked. As discussed in https://github.com/qunitjs/qunit/issues/1145.

Assert: Allow assertions after async

---

.eslintrc.json
Gruntfile.js
build/coverage-bridge.js
build/release.js
reporter/html.js
reporter/urlparams.js
runner/fixture.js
src/export.js
test/amd.js
test/main/async.js
test/main/deepEqual.js
test/main/modules.js
test/node/storage.js
test/reorder.js
test/reporter-html/window-onerror.js
test/setTimeout.js
test/startError.js

This enables the ESLint "indent" rule.
There are some limitations of this rule which would force us to deviate from the jQuery style guide, especially around full file closures (whether IIFEs or factory functions). This PR chooses to have pure IIFEs be indented 1 tab, which is further from the style guide but results in consistent indentation between pure IIFEs and factory functions.
PR #1142 is the zero-tab IIFE version.

All: Enable ESLint indent rule (one-tab indent for outer IIFE bodies)

---

docs/QUnit/skip.md
docs/QUnit/start.md
docs/assert/deepEqual.md
docs/assert/equal.md
docs/assert/notDeepEqual.md
docs/assert/notPropEqual.md
docs/assert/notStrictEqual.md
docs/assert/propEqual.md
docs/assert/strictEqual.md
docs/callbacks/QUnit.log.md
docs/config/QUnit.push.md
docs/config/QUnit.stack.md

In order to avoid `File not found` error from GitHub pages.

Docs: Remove trailing slash from some urls

---

src/core.js
src/core/config.js
src/test.js
test/logs.js
test/main/modules.js

When the first/last test in a module was skipped, it would cause the module's
before()/after() hook to not be called. This ensures those hooks will always be
called.

Core: Fix bug calling hooks with skipped tests

---

reporter/html.js

The HTML reporter does a str diff on differing numbers, which is uniquely useless. This shows the numerical difference. This checks if the values actually have typeof number, which I find preferable, but I guess checking if both values are parsable as numbers is also possible.

HTML Reporter: numerical diff of differing numbers instead of str-diff.

---

docs/callbacks/QUnit.log.md

I don't know if this worth the mention, but I found it useful to document it in case someone want to create a custom reporter.

Docs: Document 'todo' in log details object

---

README.md

In response to JSF adoption of FOSSA for license scanning. @kborchers
Congrats on the passing scan!  Here's a green badge in the PR.

Add license status

---

src/export.js
src/globals.js
test/webWorker-worker.js
test/webWorker.html
test/webWorker.js

This adds support to QUnit for running a test suite inside Web/Service
Worker context.
I have written a test for, but haven't yet added them to any of the test
suites. This is because PhantomJS has a broken Web Worker
implementation. The test runs fine in Chrome/Safari/Firefox and likely
any other browser. Guidance on how to proceed with this would be
appreciated.
Closes #1022

Core: Support running in WorkerGlobalScope

---

Gruntfile.js

https://gitter.im/qunitjs/qunit?at=58f961fecfec9192725cf2f6
> `grunt watch` will run the tests in node, but I'm pretty sure it won't reload them in any open browser windows (and in fact the webserver aspect appears to be partially broken, I'm seeing a new port claimed every time a watched file changes)

Build: Fix grunt watch

---

.travis.yml
appveyor.yml
package.json

Add node 8 to travis and appveyor, change engines list to >=4.

Core: Updates for Node.js version 8 compatibility and testing

---

docs/QUnit/module.md
src/core.js
src/core/config.js
src/test.js
test/main/modules.js

Fixes #977.
When using the nested module pattern, you can now define a multiple of each hook (`before`/`beforeEach`/`afterEach`/`after`). `before`/`beforeEach` hooks are run FIFO order and `after`/`afterEach` are run in LIFO order. This is consistent with the behavior already exhibited by those hooks when nested in modules.
cc @rwjblue (who I believe is interested in this feature for ember-qunit).

Core: Add support for multiple hooks

---

build/tasks/test-on-node.js

I came across this issue while working on implementing/testing `QUnit.module.skip`.
The issue basically was that a test (In my case, I have a test inside a `QUnit.done` callback) from a previous file was caught by `testDone` callback of the current file.
This happens because the callback `QUnit.done` defined in `test-on-node` task will be the first one to be called which will pass to test the next file without waiting for other `QUnit.done` callbacks, in case there are any, to finish their treatments.

Build: Register events after requiring test file in test-on-node task

---

bin/run.js
test/cli/fixtures/expected/tap-outputs.js
test/cli/fixtures/hanging-test/index.js
test/cli/fixtures/no-tests/index.js
test/cli/main.js

Addressing some of the feedback from https://github.com/qunitjs/qunit/issues/1132.
After this PR, the only remaining item from that issue would be to change the default for `testTimeout` which we won't be able to do until `3.0`.

CLI: Better handle various failure scenarios

---

Gruntfile.js
package.json
test/es2017/.eslintrc.json
test/es2017/async-functions.js
yarn.lock

Adds tests ensuring that using async functions for callback arguments is under test.
Closes https://github.com/qunitjs/qunit/issues/1197.
Tested locally in Phantom (which can not parse `async function() {}`) and Chrome (which can). Tests pass in both environment, and in Chrome I verified that the new tests are running.

Tests: Add tests using native async functions.

---

Gruntfile.js
src/core/utilities.js
test/index.html
test/main/utilities.js

Prior to these changes, `QUnit.objectType(async function() { });` would return `undefined` (because `Object.prototype.toString.call(async function() {})` equals `[object AsyncFunction])`).
This updates `QUnit.objectType` to fallback to returning `typeof obj` if no match was found, and adds explicit tests for the various expected inputs and outputs.
I discovered during the investigation of #1197 which is failing in qunitjs@2.3.3 due to `QUnit.objectType` not being aware of async functions (but master was fixed by a refactor done in #1188).

Core: Fallback to `typeof obj` in `QUnit.objectType`.

---

docs/QUnit/module.md

Fixes a typo "devloppement" -> "development" in docs for QUnit.module.

Docs: Fix typo in docs for QUnit.module

---

src/equiv.js

Fixes https://github.com/qunitjs/qunit/issues/1192.
There's likely a better solution here that involves "popping" each element in the array after it has finished being used, but I could not find it (the logic is complex and has multiple return points). I'd like to go with this naive approach for now and refactor later when we update this file to use ES6 syntax.

Core: Release objects from memory in equiv

---

Gruntfile.js
docs/assert/timeout.md
src/assert.js
src/test.js
test/.eslintrc.json
test/index.html
test/main/assert/timeout.js

As discussed in https://github.com/qunitjs/qunit/issues/1132.
This makes it easy to set per-test timeouts, instead of the globally configured `QUnit.config.testTimeout`.

Assert: Introduce timeout to set per-test timeout durations

---

bin/find-reporter.js
bin/qunit
test/cli/custom-reporter.js
test/cli/fixtures/expected/tap-outputs.js

Addressing #1216.
When using `qunit --reporter` you will now get a list of available reports displayed. It does not list available reporters when running `qunit --help`. I think it is best to keep the general help command minimal to ensure it stays useful for users.

CLI: List available reporters when option is specified with no value

---

Gruntfile.js
build/tasks/livereload.js
build/tasks/test-on-node.js

Continues https://github.com/qunitjs/qunit/pull/1167.
After this, you can run `grunt watch` and then visit the tests in a browser at `localhost:8000/test`. Whenever you make a file change, the browser will reload. However, `watch` only restarts after the currently executing task finishes, so if you're on the `qunit` task, it may be a bit slow.

Build: Improve watch and livereload tasks

---

.mailmap
AUTHORS.txt

This also unifies my past contributions under one persona - so far I had entries
with 2 different ways to write "ę" which treated me as 2 distinct people.

Build: Add my new name to .mailmap, update it in AUTHORS.txt

---

RELEASE.md
bin/require-qunit.js
package.json
test/cli/require-qunit-test.js

First step of fixing https://github.com/qunitjs/node-qunit/issues/136.
After merging, I will manually do another 2.4.1 release under the `qunit` package name, so that users can migrate directly from `qunitjs@2.4.1` to `qunit@2.4.1`. Then, we will deprecate `qunitjs@2.4.1` with a message stating that users should switch to the `qunit` package.
All future releases will then be under the `qunit` name.
As for the current `qunit` package, we will be switching that to be released as `node-qunit`. I've reached out to the owner of the current `node-qunit` package (which is deprecated) and he is fine with us taking over the name.

All: Rename package to QUnit

---

src/test.js
test/cli/fixtures/notrycatch/returns-rejection.js
test/cli/main.js

Avoid adding a rejection handler when `notrycatch` is set. This enables much nicer "break on uncaught" exception ergonomics.
As suggested in #1154, I added the failing test to the set of tests that only run on node. However, I did not add an `unhandledRejection` handler due to the deprecation added in Node 7 which suggests that a future Node version will `process.exit(1)` for unhandled rejections (ultimately meaning any tests we build around it will need to be refactored). Instead, I used the CLI test system to execute a test file with `notrycatch` set and ensured that the rejection reason ended up in the processes stderr.  I also confirmed that the test fails before the changes in `src/test.js` (due to the `stderr` output being empty) and passes after.
I took care to preserve @NaridaL's …

Ensure `notrycatch` avoids installing rejection handler.

---

bin/run.js
reporter/html.js
src/core.js
src/core/on-unhandled-rejection.js
test/cli/fixtures/expected/tap-outputs.js
test/cli/fixtures/unhandled-rejection.js
test/cli/main.js
test/index.html
test/reporter-html/unhandled-rejection.js

Prior to this change, an unhandled exception in a promise that was not returned from the `test` callback would not cause test failure.
For example, the following (using default out of the box settings) results in test failures:
```js
test('native promises cause an unhandled rejection', function(assert) {
// imagine this was "deep" inside various method calls
setTimeout(function() {
throw new Error('whoops!');
});
// other things that we are trying to test
assert.deepEqual(someMethod(), ['one', 'two']);
});
```
And this (prior to this PR) would result in a passing test suite:
```js
test('native promises cause an unhandled rejection', function(assert) {
// imagine this was "deep" inside various method calls
Promise.resolve().then(function() {
throw new Error('whoops!');
});
// other things …
```

Ensure unhandled rejections cause test failure.

---

src/core.js
src/core/processing-queue.js
src/test.js
test/main/promise.js

Per https://github.com/qunitjs/qunit/issues/1245 these can build up and cause larger test suites to have some significant performance hits. They don't seem to be needed and I can't find any reason in the history as to why they are needed. In fact, the one comment I can find relating to them is a suggestion to [remove it](https://github.com/qunitjs/qunit/pull/653#discussion_r17195204).

Core: Remove delay from setTimeouts in processing code

---

docs/assert/rejects.md
src/assert.js
test/main/assert.js

Closes https://github.com/qunitjs/qunit/issues/1204

Assert: Add `assert.rejects`.

---

docs/assert/timeout.md

Add example showing use of `assert.timeout()` in an async test.

Docs: Add example for async test with assert.timeout

---

runner/fixture.js
test/main/test.js

This change leverages `Node.prototype.cloneNode` to deeply clone the original `qunit-fixture` before any tests have started, then for each test replaces (using `Node.prototype.replaceChild`) the current `qunit-fixture` with a clone of the original.
Fixes https://github.com/qunitjs/qunit/issues/1224.

HTML Reporter: Ensure attributes on qunit-fixture are reset.

---

src/test.js
test/main/assert/step.js

Assert: Fail test when using step inside a test without verifySteps

---

src/test.js
test/main/promise.js

Fixes https://github.com/qunitjs/qunit/issues/1229.
When a Promise rejects, we were previously only releasing the processing lock from that Promise. Now we'll release all processing locks when that occurs, similarly to what we do for exceptions that occur during a non-Promise test.

Core: Release all processing locks when Promise rejects from a test

---

docs/assert/rejects.md

Hi everyone,
This PR contains the following changes:
1. Marking the second parameter of `assert.rejects()` as optional
2. Adding `error object` as possible values of `expectedMatcher`
3. Removing an unexpected `throw` statement in examples

Rejects docs updates

---

.travis.yml

Split off the Travis changes from #1235.

Build: Use Node 9.x for matrix, cache node_modules

---

src/assert.js
test/main/assert/step.js

Fixes https://github.com/qunitjs/qunit/issues/1266
The test setup is a bit awkward to verify this fix, so if anyone has a better idea, let me know!

 Assert: Clone actual steps array to avoid passing internal reference

---

src/assert.js
test/main/assert.js

Fixes https://github.com/qunitjs/qunit/issues/1268
Bulk of changes are whitespace; might want to add `?w=1` to the URL when viewing the diff.

Assert: Support rejecting falsy values against no matcher in rejects

---

bin/run.js
src/core/processing-queue.js
test/cli/fixtures/expected/tap-outputs.js
test/cli/main.js
test/startError.html
test/startError.js

Fixes https://github.com/qunitjs/qunit/issues/569 (finally).
We throw an error if no tests are run. Optionally includes a more specific message if a filter is being used. The error should report as a global failure via the `QUnit.onError` handler.
Need to add some new tests to verify behavior.

Core: Throw error if no tests are run

---

bin/qunit
bin/require-from-cwd.js
bin/run.js
test/cli/fixtures/expected/tap-outputs.js
test/cli/fixtures/node_modules/require-dep/index.js
test/cli/fixtures/node_modules/require-dep/module.js
test/cli/fixtures/node_modules/require-dep/package.json
test/cli/main.js

This PR implements a `--require` option for the CLI. It allows for any number of dependencies or files to be `require`d prior to the test suite run actually starting.
Fixes https://github.com/qunitjs/qunit/issues/1222

CLI: Implement --require option

---

src/core/processing-queue.js
test/reorder.js

As mentioned in this comment: https://github.com/qunitjs/qunit/pull/1260/files#r169779552
(Note: Test has some weird behavior in PhantomJS, but verified it works as expected in Chrome, Safari, and FireFox)

Core: Ensure late-add high-priority tests are inserted in proper order

---

reporter/html.js
test/reporter-html/reporter-html.js

fix: disable autocomplete on module search input

---

docs/Gemfile
docs/Gemfile.lock
docs/_config.yml
docs/assert/async.md
test/main/modules.js

Proof of concept for https://github.com/qunitjs/qunit/issues/1289.
* Fix broken link to /QUnit/stop which no longer exists.
* For incoming links from elsewhere, set up a redirect from there
to the closest currently related page, which is /assert/async.
The redirect logic uses the Jekyll Redirect From plugin, which
is also allowed and preinstalled on GitHub Pages. For local dev,
add the same name and version of that gem, per
<https://pages.github.com/versions/>.

Docs: Fix broken QUnit.stop link from assert/async and add redirect

---

docs/QUnit/module.md
docs/QUnit/start.md
docs/QUnit/test.md
docs/assert/async.md
docs/assert/deepEqual.md
docs/assert/equal.md
docs/assert/expect.md
docs/assert/notDeepEqual.md
docs/assert/notEqual.md
docs/assert/notStrictEqual.md
docs/assert/ok.md
docs/assert/strictEqual.md
docs/assert/throws.md
docs/config/QUnit.dump.parse.md

Fixes #1289.
----
Follows proof-of-concept from https://github.com/qunitjs/qunit/pull/1291 which worked. <https://api.qunitjs.com/QUnit/stop> now redirects to <http://api.qunitjs.com/assert/async>.

Docs: Set up redirects for old urls

---

docs/QUnit/module.md
docs/QUnit/start.md
docs/QUnit/test.md
docs/assert/async.md
docs/assert/deepEqual.md
docs/assert/equal.md
docs/assert/expect.md
docs/assert/notDeepEqual.md
docs/assert/notEqual.md
docs/assert/notStrictEqual.md
docs/assert/ok.md
docs/assert/strictEqual.md
docs/assert/throws.md
docs/config/QUnit.dump.parse.md

Follows-up a7ccfcb.
Having an entry for both "foo" and "foo/" is supported, however
a problem happens if the "foo" part contains one or more dots.
Normally, "foo" creates `_site/foo.html` and
"foo/" creates `_site/foo/index.html`. However, if the name
contains a dot, then the file name won't have ".html" appended.
This causes the Jekyll build to fail because it cannot, for example
create "_site/QUnit.module" as both a file and a directory.
```
jekyll 3.4.3 | Error:
> File exists @ dir_s_mkdir - qunit/docs/_site/QUnit.module
```
Rather than trying to find a way to enforce `.html` in the filename,
I found out that the Jekyll plugin actually handles redirects for
slashless variants as well, so we only need the versions with a slash
and everything will continue to work fine.

Docs: Fix Jekyll build (remove conflicting file/dir names)

---

yarn.lock

without this update `node-gyp` failed when running on Node 10.3.0
/cc @trentmwillis

Update `fsevents` subdependency for Node 10 compat

---

src/assert.js

This is an extract of other work and the result of a code review. Check the implementation of pushResult and all its other spots of usage: no return value is ever produced.

pushResult() doesn't ever return a value: it's always undefined/void.

---

bin/run.js
package-lock.json
package.json
yarn.lock

I think chokidar is great, but the ergonomics around native dependencies today in node really painful. Although chokidar pre-builds, users switching nodes, or with old yarn.lock files, or failed pre-build downloads, or behind firewall usages cause a fallback to requiring a working compiler toolchain. Requiring that, very much increases the barrier of entry, and support load for tooling/cli maintainers.

[fixes #121] chokidar -> sane

---

package-lock.json
package.json
yarn.lock

Ref #1302.
Bumped the version of `grunt-coveralls` to `2.0.0` and then ran `yarn install` and `npm install` to regenerate the lock files. Looks like it should resolve the CVE as `hoek` is no longer listed in either of the lock files.

Build: Upgrade grunt-coveralls to 2.0.0

---

package.json
yarn.lock

PR in sane: https://github.com/amasad/sane/pull/130
This removes another native dependency hazard, now there are no native dependencies required.

bump sane, this drops another native extension.

---

Gruntfile.js
package-lock.json
reporter/html.js
test/reporter-html/xhtml-single-testid.xhtml

See https://github.com/qunitjs/qunit/issues/1255 . There was a tag without a closing / that confused the browser when using XHTML.

HTML Reporter: Fix XHTML output (issue 1255).

---

reporter/html.js
test/reporter-urlparams-hidepassed.html
test/reporter-urlparams-hidepassed.js

What? 
- make hidepassed remove item from div rather than just hiding it
Why?
When running large test suites, rendering test output for all passing tests will cause the page to become unresponsive.
```
> document.querySelector('#qunit-tests').children.length
> 24280
```
The above output is from:
```
81 tests completed in 97301 milliseconds, with 2 failed, 2 skipped, and 0 todo.
210 assertions of 217 passed, 7 failed.
```
While the tests are running, the page becomes more and more unresponsive while appending output items. `24280` only represents the immediate children, the full child tree contains `146780` nodes.
```
> const tests = document.querySelector('#qunit-tests');
> tests.getElementsByTagName("*").length
> 146780
```
Solution?
- actually remove child item when it passes

HTML Reporter: remove test item when hidepassed is set to true

---

src/core/utilities.js
src/reports/suite.js
src/reports/test.js
test/performance-mark.html
test/performance-mark.js

```
[17:05:03] not ok 10 Chrome 69.0 - [undefined ms] - <undefined> - Global error: Uncaught SyntaxError: Failed to execute 'measure' on 'Performance': The mark 'qunit_test_start' does not exist. at http://localhost:7357/assets/test-support.js, line 4335
While executing test: ...
```

Core: guards performance.measure to not throw and cause tests to fail

---

reporter/html.js
src/core/onerror.js
test/onerror/inside-test.js
test/reporter-html/window-onerror.js

Currently, when QUnit catches an uncaught error in its window.onerror
handler, it reports it with a source of `fileName + ":" + lineNumber`.
While it's not standard, most modern browsers include an errorObj
argument to window.onerror, which can be used to get a more complete
stacktrace
([source](https://blog.sentry.io/2016/01/04/client-javascript-reporting-window-onerror)).
This change modifies the HTML reporter and the `QUnit.onError` method to
do that.

Report full stack trace for uncaught errors if possible

---

Gruntfile.js
docs/callbacks/QUnit.begin.md
docs/callbacks/QUnit.done.md
docs/callbacks/QUnit.log.md
docs/callbacks/QUnit.moduleDone.md
docs/callbacks/QUnit.moduleStart.md
docs/callbacks/QUnit.on.md
docs/callbacks/QUnit.testDone.md
docs/callbacks/QUnit.testStart.md
package.json
rollup.config.js
src/core.js
src/core/logging.js
src/core/processing-queue.js
src/promise.js
src/test.js
test/callbacks-promises.html
test/callbacks-promises.js
test/cli/fixtures/expected/tap-outputs.js
test/cli/main.js
yarn.lock

Addresses #1228 
This change consist of several parts to enable QUnit callbacks to handle promises like:
```
QUnit.moduleDone(function() {
return new Promise(function(resolve) {
// do some async things
resolve();
});
});
```
1. Make advanceTaskQueue handle promises returned from each task
Each QUnit Test consist of multiple tasks, which handles setup, test execution, teardown and reporting of test results.
"advanceTaskQueue" is the function that controls the execution flow of tasks from each test. Hence, this needs to be able to handle promises that are returned by tasks.
2. 'runLoggingCallbacks' returning a promise
'runLoggingCallbacks' is the function used to execute callback (eg. begin, moduleStart, testStart, testDone, moduleDone, done) function that is registered. This will now …

Core: Adding promise handling on qunit callbacks: begin, moduleStart, testStart, testDone, moduleDone

---

reporter/html.js
test/reporter-html/reporter-html.js

the running class was removed and no existing tests catch this, I added it back and now added with it a test to ensure this doesn't happen again.

Core: adds back running class to items and adds tests

---

Gruntfile.js

When something is locally running on port 8000 already, the
tests consistently fail. For now, spread the approach we used
for livereload and allow it to be specified by the user.
This is a pretty poor user experience, but until we find a way
to not need, or do differently, the urls in grunt-contrib-qunit,
we need to know it synchronously while calling grunt.initConfig,
which basically leaves manual CLI options as the only option.

Build: Add --connect-port for Gruntfile to override 8000

---

test/cli/helpers/execute.js
test/cli/watch.js

Follows-up 362e2416669, which removed 'npm link' from the 'test:cli'
script command.
Initially, I thought the reason the child processes can't find qunit is due to our use of `execa.shell` instead of regular `execa`. Specifically, `execa.shell()` spawns a process that starts with a new shell and no inherited environment variables. `execa()` on the other hand inherits environment variables like PATH by default, and it also has a `preferLocal` option that ensures node_modules/.bin is in the`PATH` even if you're running the tests without `npm run ..` (e.g. if you'd use `bin/qunit test/cli/*.js` directly).
Switching to `execa()` is non-trivial because it requires an array as input and there aren't built-in or trust-worthy modules that parse a command string into an array. Trying it with …

Tests: Unbreak test:cli due to unknown 'qunit' command

---

Gruntfile.js
reporter/html.js
test/reporter-html/test-escape-details-source.js
test/reporter-html/xhtml-escape-details-source.xhtml

Fix an unescaped details.source  in innerHTML.
It became apparent when using .xhtml (application/xml+xhtml) but may
have other XSS issues (see
https://en.wikipedia.org/wiki/Cross-site_scripting ) in plain HTML.
The new test gets stuck before the production code fix and completes
successfully and promptly after applying it.

HTML Reporter: Fix an unescaped details.source.

---

appveyor.yml

The AppVeyor build is currently failing due to Node 4 not
being supported anymore, whih is intentional and removed from
the Travi CI config already, but in reviewing #1288, I forgot
about AppVeyor :)

Build: Remove Node 4 from AppVeyor test matrix

---

package.json
src/cli/find-reporter.js
src/cli/require-from-cwd.js
src/cli/run.js
src/cli/utils.js
test/cli/fixtures/expected/watch-tap-outputs.js
yarn.lock

See commit messages.
Fixes #1342.

CLI: Reduce the size of the dependencies tree

---

src/assert.js
test/cli/fixtures/expected/tap-outputs.js
test/main/assert.js

Report the `actual` (Error object) as a string. And report an `expected` RegExp or Error object also in its string form.
Currently, they were reported as their objects, which in the generic js-reporters module was just printed as an empty object without any properties because instances of RegExp and instances of Error both have no own properties that are enumerable.
Fixes #1333.

Assert: Report RegExp/Error as strings from rejects()/throws()

---

package.json
src/cli/run.js

* Added `ready` event.
* Improved Linux support for recursive watching (changes that happen during the debounce from new directories are now reported as well).
The above two points were effectively temporary regressions in qunit master from 94fa19f899, which are now restored.
When collaborating with upstream and improving the unit tests, I found various bugs with Node.js itself (or actually its upstream, libuv), which couldn't be easily worked around. These were only bugs about there being extra events in addition to the correct ones, which is fine from our perspective; it just means we potentially re-run the tests more often (in practice, not even that, given we debounce).
* https://github.com/nodejs/node/issues/25301
* https://github.com/nodejs/node/issues/25290

CLI: Update node-watch to 0.6.0

---

.eslintrc.json

Otherwise, the proposed PR for qunitjs/jquery-release (https://github.com/qunitjs/jquery-release/pull/2), is unable to get "grunt" to pass on qunitjs/qunit because it's clone will be in a subdirectory of itself, which then fails as follows:
> ~/Dev/qunit-release/__release/repo/test/reporter-html/window-onerror-preexisting-handler.html
>  9:27  error  'onerrorCallingContext' is assigned a value but never used  no-unused-vars
This is because ESLint is walking up from __release/repo and finding an unrelated `.eslintrc` file in *that* repo.

Build: Set "root: true" in eslintrc

---

bin/.eslintrc.json
bin/qunit.js
package.json
src/cli/.eslintrc.json
src/cli/require-qunit.js
yarn.lock

[eslint-plugin-node](https://github.com/mysticatea/eslint-plugin-node) helps check for a large number of issues (deprecated APIs, requires from unpublished files, missing dependencies, etc).
---
The adds linting to ensure issues like the one reported in #1367 would fail CI:
```
Running "eslint:js" (eslint) task
/Users/rjackson/src/qunitjs/qunit/bin/qunit.js
3:1   error  This file needs shebang "#!/usr/bin/env node"  node/shebang
6:22  error  "../src/cli/run" is not published              node/no-unpublished-require
7:31  error  "../src/cli/find-reporter" is not published    node/no-unpublished-require
✖ 3 problems (3 errors, 0 warnings)
1 error, 0 warnings potentially fixable with the `--fix` option.
Warning: Task "eslint:js" failed. Use --force to continue.
Aborted due to warnings.
``` …

Fix (and add tests) missing required files in 2.9.0.

---

package.json
yarn.lock

This adds support for Yarn Plug'n'Play if Yarn 1.13+ is used. I'm not saying `qunit` supports it yet, but at least the import resolution should start to work.
/cc @arcanis @rwjblue

Update `resolve` to v1.9.0

---

reporter/html.js

Using `style` attribute of an Element requires Content-Security-Policy (CSP) `style-src 'unsafe-inline'`. This makes testing that a library or an application does not violate a strict CSP more difficult.

fix: HTML reporter should not require CSP style-src 'unsafe-inline'

---

docs/config/QUnit.config.md

According to the documentation above, both are lowercase.

Fix the casing for autostart and noglobals

---

src/test.js
test/cli/fixtures/expected/tap-outputs.js
test/cli/fixtures/timeout/index.js
test/cli/main.js

Core: Ensuring semaphores are balanced when timeout occurs

---

README.md

Migrated from deprecated Travis CI dot-org and deprecated GitHub service hooks,
to dot-com via GitHub Apps integration.

Docs: Update Travis badge

---

package.json
yarn.lock

https://github.com/yuanchuan/node-watch/releases/tag/v0.6.1
* Fixed a race condition where a short-lived file
could cause the wrong result.
* Fixed a bug affecting Windows installations.

Build: Update node-watch to 0.6.1

---

src/qunit.css

The tested site can override the styling of buttons, which causes the
displayed content to 'jump' around while tests are running, so ensure
that all buttons in qunit elements are set to inital font size, border
and background.
With modules that have long names, the filter list becomes un-useable,
so allow them to grow using min-width rather than fixed width

CSS: Tweak CSS to address dropdown and button styles

---

reporter/html.js
test/reporter-html/reporter-html.js

Display progress and runtime while test suite is executing

---

docs/assert/timeout.md
src/assert.js
src/test.js
test/main/assert/timeout.js

This reset any current timeouts by canceling and setting up a new timer.
Usecase: https://github.com/emberjs/ember-qunit/issues/496

Core: reset testTimeout on assert.timeout if config.timeout has already been set

---

docs/callbacks/QUnit.log.md

The link <https://api.qunitjs.com/QUnit.log/> used to work.

Docs: Repair old url for QUnit.log with redirect

---

docs/QUnit/index.md
docs/_layouts/default.html
docs/_layouts/wrapper.html
docs/callbacks/index.md
docs/config/index.md

Fixes #1396
Also fixes some discrepancies between the sidebar and the top navigation.

Docs: rename "Main assertions" page to "Main Methods"

---

package-lock.json

This happens automatically when `npm install` runs.

Build: Bumps package.lock verstion to 2.9.4-pre

---

reporter/html.js
src/qunit.css

The objective of this pull request is to correct the tab order for the toolbar filters. Currently, the tab order for the **Module** and **Filter** items in the toolbar are in reverse order (right-to-left for English) as described by Issue #1428:
Issue #1428 - Tab order for "Module" and "Filter" items is reversed in toolbar
The changes applied in this pull request wrap the two toolbar filters into a single container SPAN element. This new container has a `float: right` style that acts as a substitute for the original `float` styles assigned to each of the two toolbar filters. When the individual `float` styles are removed from the toolbar filters, then the order of the corresponding DOM elements (also the tab order) for these filters will no longer be the reverse of the visual order.

Correct tab order for toolbar filters

---

docs/QUnit/module.md
docs/QUnit/only.md
src/module.js
src/test.js
test/module-only.js
test/only.js

WIP alternate implementation of #1434: modifying the way `only` behaves instead of adding a new method.
TODO:

Core: Connected to #1434: run all `only` tests

---

package-lock.json
package.json
reporter/html.js
rollup.config.js

Sample implementation of: https://github.com/qunitjs/qunit/issues/1438 ([`fuzzysort`](https://github.com/farzher/fuzzysort)-based).
Below search results with different keywords (on `test/index.html`). The examples below use different values of `fuzzysort`'s `threshold` option.
`-10000` is the value used in `fuzzysort`'s documentation: [How To Go Fast · Performance Tips](https://github.com/farzher/fuzzysort#how-to-go-fast--performance-tips) section.
Search: "assert".
Search: "beforeEach".
Search: "promiseaware".
Search: "script".
Search: "assert".
Search: "beforeEach".
Search: "promiseaware".
Search: "script".

HTML Reporter: Fuzzy search using fuzzysort

---

.travis.yml
package-lock.json
package.json
test/cli/fixtures/expected/tap-outputs.js
test/cli/fixtures/memory-leak/.eslintrc.json
test/cli/fixtures/memory-leak/index.js
test/cli/main.js

Node 6-10:
> at process._tickCallback (internal/process/next_tick.js…)
> at ontimeout (timers.js…)
Node 12-14:
> at processTicksAndRejections (internal/process/task_queues.js…)
> at listOnTimeout (internal/timers.js…)
Also update the memory-leak test to use a different strategy
because the V8 native `%GetWeakSetValues` function no longer
exists as of V8 7.1 (or 8.1, not sure) per
<https://chromium.googlesource.com/v8/v8/+/0cf4a0f82f8f810519ba0d4b3b01adef0a0a6c1d>
<https://chromium-review.googlesource.com/c/v8/v8/+/1238574>.
Instead, inspect a heap snapshot and validate it that way.
Also expand the test so that we first verify our logic actually
works, for easier debugging in the future.
As of Node 14, `fs.watch` can throw ERR_FEATURE_UNAVAILABLE_ON_PLATFORM,
which is handled by node-watch …

All: Update node-watch dependency and test fixtures for Node 12+

---

src/qunit.css

There are currently two places where we use buttons:
* The toolbar, with the filter "Go" button and the "Apply" and "Reset"
buttons for the module dropdown.
* The test results, with the temporal "Abort" button.
Fixes https://github.com/qunitjs/qunit/issues/1437.

CSS: Scope QUnit UI button style to not affect #qunit-fixture

---

src/qunit.css

There are currently two places where we use buttons:
* The toolbar, with the filter "Go" button and the "Apply" and "Reset"
buttons for the module dropdown.
* The test results, with the temporal "Abort" button.
Fixes https://github.com/qunitjs/qunit/issues/1437.

CSS: Scope QUnit UI button style to not affect #qunit-fixture (2.10.x backport)

---

docs/assert/false.md

When visiting <https://api.qunitjs.com/assert/false>, the page
lacks the expected document title of `false | QUnit API Docs`.
This is because `false` got intepreted as a boolean value rather
than the string that it is meant to be (Thanks YAML!).
------
Follows-up https://github.com/qunitjs/qunit/commit/0a0b7b8b275e1b4ec6a2b49df7bf0db1f98b2f74.
/cc @ventuno

Docs: Restore page title of assert.false

---

Gruntfile.js
reporter/html.js
test/reporter-urlparams-hidepassed.js

Fixes #1208
Also adds the test file with the for hidepassed to the list of tests to be run.
I don't think there is test coverage on my changes to the `toolbarChanged` method.

HTML Reporter: Hide skipped tests when hidepassed is set

---

.gitignore
.travis.yml
package-lock.json
package.json
src/cli/require-from-cwd.js
src/cli/require-qunit.js
test/cli/fixtures/require-from-cwd/node_modules/qunit/index.js
test/cli/require-qunit-test.js

Per <https://github.com/nodejs/Release>, Node 6 and 8 have
reached EOL in 2019.
This allows us to drop the 'resolve' package as dependency,
which is no longer needed as of Node 8.

Core: Drop support for Node 6 and Node 8, require Node 10+

---

src/globals.js
test/.eslintrc.json
test/cli/.eslintrc.json
test/main/assert.js
test/main/assert/step.js
test/main/utilities.js
test/only.js
test/reporter-html/unhandled-rejection.js
test/reporter-html/window-onerror.js
test/webWorker-worker.js

Follows-up 474a708, which added fuzzysort.js, which has an
undocumented dependency on ES6 Map (whilst publishing its code
in UMD/ES5-syntax).
Restore IE 10 compat by adding a simple inline fallback
(it only needs to work with strings).
Also:
* Restore ESLint settings on test/main/ to explicitly disable
es6. This used to be the default (we enable es6:true on /src/
and /test/cli), but now that ESLint enables it by default we need
to disable it to flag its use.
* Fix the handful of syntaxes that were introduced and caused
tests to fail as a result.
Ref https://github.com/qunitjs/qunit/pull/1440.

HTML Reporter: Add basic ES6 Map fallback for fuzzysort.js

---

package-lock.json
package.json
src/cli/run.js
src/cli/utils.js
test/cli/fixtures/expected/tap-outputs.js

When using a glob or directory argument, we currently recursively traverse the entire working directory (except for `.git` and `node_modules`) and then filter out results later with Minimatch. This is inefficient to say the least, and is especially noticable on large repositories.
I looked into a bunch of glob libraries but couldn't find any that uphold our security and simplicity principles, in so far that most of them bring in far too many dependencies that I can't feasibly audit or keep up with and (unfortunately) most likely the library author hasn't audited or trusts deeply either to e.g. not get compromised or taken over in subtle ways.
Except for one, `tiny-glob`, this seems to fit the bill nicely and would be a great library to boost through the QUnit community. I instrumented it …

CLI: Further improve startup performance

---

package-lock.json
package.json
test/cli/fixtures/expected/tap-outputs.js

Relevant changes:
* Reporter: Align `actual` with `expected` in TapReporter. (Robert Jackson)
https://github.com/js-reporters/js-reporters/pull/107

Build: Update to js-reporters 1.2.3

---

src/cli/require-qunit.js

If the project using QUnit has a local qunit.json file in the
repository root, then the CLI was unable to find the 'qunit'
package. Instead, it first found a local 'qunit.json' file.
This affected an ESLint plugin with a 'qunit' preset file.
This bug was fixed in Node 12, and thus only affects Node 10 for us.
The bug is also specific to require.resolve(). Regular use of
require() was not affected and always correctly found the
local package. (A local file would only be considered if the
require started with dot-slash like `./qunit`.)
Ref https://github.com/nodejs/node/issues/35367.
Fixes https://github.com/qunitjs/qunit/issues/1484.

CLI: Fix 'qunit' require error on Node 10 if qunit.json exists

---

reporter/html.js
runner/fixture.js
src/core.js
src/core/processing-queue.js
src/core/utilities.js
src/export.js
src/reports/suite.js
src/reports/test.js
src/test.js

The pattern of checking `A` to decide whether `B` is safe to use is imho an anti-pattern and reduces confidence in the code. This was previously the case for `setTimeout`, `performance` and `document`.

Clean up internal access to document and performance globals

---

Gruntfile.js
src/assert.js
test/es2017/throws.js
test/main/assert.js

fixes #1389
added positive and negative unittests

Assert: Allow fat arrow functions in throws expected handler

---

reporter/html.js

Follows-up 0780127c7f64, which changed the code to use QUnit.config.modules directly. This meant the list is no longer
sorted, however. I filed https://github.com/qunitjs/qunit/issues/1487 to look into that.
Depending on the outcome of that, we can bring this back in some form after the refactoring of https://github.com/qunitjs/qunit/issues/1487.

HTML Reporter: Remove unused 'moduleList' arrray

---

docs/QUnit/test.md
src/core.js
src/test.js
test/main/test.js

Fixes #1402 
```
QUnit.test.only === QUnit.only
QUnit.test.todo === QUnit.todo
QUnit.test.skip === QUnit.skip
```
#1402 called out these QUnit.test variants as aliases _to_ the main QUnit functions, but to keep the code modular, I reversed that in the implementation to make the _main_ QUnit functions aliases to the test implementations. Those are really the "shortcuts" at that level, and Test holds onto the real implementations (as it always had). These methods are now encapsulated and exposed only through the Test function/object, no longer as exported functions.
Our existing tests still use the main QUnit methods, which I think is perfectly valid.
I doc'ed these new aliases in Test.md, pointing to the existing main QUnit methods. I did _not_ touch the main only/todo/skip docs to point …

Provide QUnit.test aliases for only/todo/skip

---

docs/config/QUnit.extend.md
reporter/html.js
src/core.js
test/main/utilities.js

Fixes #1491 
Backfilled a few unittests for sanity-checks and coverage
QUnit.extend issues a warning that it is to be deprecated in QUnit 3.0, and recommends `Object.assign`. (do we want an MDN hyperlink?)
The core `extend` utility is still warning-free, and used internally in many places. In QUnit 3.0, those can move to `Object.assign` as well.
Added deprecated status on docs, guessing that this would land in 2.12.

Deprecate QUnit.extend

---

package-lock.json
package.json

node-watch:
* Changelog: https://github.com/yuanchuan/node-watch/blob/0.7.0/Changelog.md
* Diff: https://github.com/yuanchuan/node-watch/compare/0.6.4...0.7.0
* Summary:
- Remains dependency-free.
- Audited by me.
- No notable changes for us (adds a new option).
commander:
* Changelog: https://github.com/tj/commander.js/blob/v6.2.0/CHANGELOG.md
* Diff: https://github.com/tj/commander.js/compare/v6.0.0...v6.2.0?w=1#files_bucket
* Summary:
- Remains dependency-free.
- Audited by me.
- No notable changes for us (fixes bugs with options we didn't use,
and adds new options).

CLI: Update "node-watch" and "commander" dependencies

---

Gruntfile.js

A continuation of what #1493 was getting at - the right test _phases_ were being run, but many testpoints were _missed_.
I isolated that the "sandboxed-iframe.html" test was the one causing issues in the browser tests, though only in coverage mode. I admit I don't understand what that iframe and injection step is doing, but it was leaking into the other tests queued up, and resulting in a lot of testpoints being omitted.
With it listed first, we get 129 tests completed with 210 assertions, and overall code coverage at 61%.
Moving it to the end, we get **348** tests completed with **949** assertions, and overall code coverage at **88%**.

Build: fix missing coverage from main browser tests

---

reporter/html.js

Use console.warn to message that PhantomJS is deprecated
I do have reservations about how visible this `console.warn` messaging may be (looks like different setups may suppress such outputs?), but it's a soft, opportunistic message before removal in 3.0.

HTML Reporter: deprecate PhantomJS

---

CONTRIBUTING.md
package-lock.json
package.json

I've had to manually disable (and subsequently undo) this in package.json everytime I run `npm i`  or `npm ci`.
A secure dev environment must not allow npm scripts to write to .git/hooks. I use such an environment, and commitplease is
incompatible with that.
We could register it as part of npm-test or something else, but in practice it seems more often in the way than not. Especially as it is not very compatible with a PR-workflow where you might have fixup commits. I personally don't prefer that workflow, but it's what works best within GitHub (today). If that gets better, and we can assume each commit stands on its own, we could add this back as part of npm-test and/or in CI.
For now, just remove it and I'll take it on us as team to edit this as needed when performing the merge …

Build: Remove 'commitplease' hook in favour of contribs doc

---

reporter/es6-map.js
rollup.config.js
src/globals.js

On IE6-8 and in PhantomJS, our partial ES6 Map implementation was leaking as global variable.
Follows https://github.com/qunitjs/qunit/commit/2f2eaba36e9c4be7eaa82a71107ea5f66c7b1519.
Fixes https://github.com/qunitjs/qunit/issues/1508.

HTML Reporter: Avoid leaking `Map` variable in older browsers

---

src/test.js
test/main/test.js

This doesn't affect end-users, since nesting QUnit.test() calls
isn't supported. In our own unit tests, we assert early bail out
behaviour for passing invalid arguments to QUnit.test(), and naturally
we do this from inside another QUnit.test() call.
The previous code left bailed out *after* we had already registered
the test and handed out references to reporting code. This meant
that it would count this as two tests of which one had an unknown
state, which js-reporters casts to a failed test.
This wasn't caught in CI because:
- When we run the test via the HTML Reporter and via the
test-on-node task, we report it via the legacy QUnit.testDone()
and QUnit.done() which didn't pay attention to this half-known
test.
- And we don't currently run this test via the QUnit CLI
(if we did, it …

Core: Fix test counter bug when nesting invalid test functions

---

src/dump.js

Follows-up a5c3b3075efbd0, in which part of this was accidentally removed from the source. This commit now restores it, resolves the canonical opensource.org URL, and includes a formatted copy of the license itself.
Fixes https://github.com/qunitjs/qunit/issues/1518.

Dump: Add copy of jsDump license header

---

src/qunit.css

CSS change to keep test headers fixed at the top and make test results scrollable. Much improved dev experience.
Fixes #1512

HTML Reporter: headers fixed, tests scrollable

---

package-lock.json
package.json

Ref https://github.com/qunitjs/qunit/issues/1522.
> ### Verify publication: tiny-glob 0.2.6 -> 0.2.8
> 
> ```
> $ npm info tiny-glob@0.2.8
> 
> dependencies:
> - globalyzer: 0.1.0
> - globrex: ^0.1.2  
> 
> maintainers:
> - terkelg <terkel@terkel.com>
> 
> published a week ago by terkelg <terkel@terkel.com>
> ```
> 
> ✅ It was published by the same account as previously.
> ✅ No new maintainers were added.
> ✅ No new dependencies were added.
> ⚠️ Some dependency versions changed:
> 
> ```diff
> -        "globalyzer": "^0.1.0" -> 0.1.4
> +        "globalyzer": "0.1.0" -> 0.1.0
> -        "globrex": "^0.1.1" -> 0.1.1
> +        "globrex": "^0.1.2" -> 0.1.2
> ```
> 
> ### Verify publication: globalyzer 0.1.4 -> 0.1.0 (downgrade)
> 
> ```
> $ npm info globalyzer@0.1.0
> 
> globalyzer@0.1.0
> …
```

Build: Upgrade `tiny-glob` to 0.2.8

---

src/core.js

Flattening logic and pushing local vars down in scope
Inverted some if/else's to be simpler and avoid as much nesting as possible.
Incremental cleanup towards deprecating QUnit.load (#1502) that I wanted to isolate and keep driving forward

Core: Simplify start() and begin() logic to improve readability

---

src/core.js
src/core/config.js
src/core/logging.js
src/core/stacktrace.js
src/core/utilities.js
src/dump.js
src/equiv.js
src/globals.js
src/test.js

A followup task triggered by https://github.com/qunitjs/qunit/pull/1528#discussion_r549472922
This targets the `src` directory, converting all `var` instances to either `let` or `const` as appropriate.
This endeavor also allowed me to scope a few variables more locally, and (at least on paper) improving performance by deferring work beyond early returns.
The largest churn by far was in `equiv.js`, where some indents were affected (try to diff ignoring whitespace). Otherwise the actual changes were similarly straightforward.

Core: convert var to let/const in src

---

docs/assert/index.md

Found links in various tutorials and blogposts.
This was an implicit overview powered by the old WordPress site.
http://web.archive.org/web/20160309213934/https://api.qunitjs.com/category/assert/

Docs: Add /category/assert/ legacy redirect

---

src/assert.js
src/test.js

For an async test, we normally remember the assigned timeout amount, and the actual scheduling and enforcement of the timeout doesn't happen until after the test callback returns.
If the test doesn't happen to be asynchronous, then the amount is discarded and we simply move on to the next test.
Sometimes, the timeout ID stored in `config.timeout` for a previous async test would remain and thus caused `assert.timeout()` to wrongly think it was called twice in the same test, and tries clear and reschedule it, when actually it is clearing nothing and scheduling the first timeout and doing so before the test callback has returned.
Thus when the test is over and we "ignore" the timeout, QUnit then got confused thinking it's an async test and thus waits until it times out.
Fix this by making …

Assert: Fix assert.timeout() bug causing a non-async test to fail

---

README.md
RELEASE.md
build/dist-replace.js

Make QUnit releases deterministic by embedding a known date instead of the "current" date and time.
Adopt the standard mechanism for this based on <https://reproducible-builds.org/docs/source-date-epoch/> which involves an environment variable named `SOURCE_DATE_EPOCH` set to a UNIX timestamp. This requires one line of code to then reformat to the ISO date were prefer, but this seems worth it.
In an earlier iteration on this patch, I had the Git CLI format it that way from the start, like so:
```
QUNIT_RELEASE_DATE="$(git show -s --format=%cd --date=short HEAD)"
```
Instead, we use:
```
SOURCE_DATE_EPOCH="$(git log -s --format=%at -1)"
```
... and dist-replace.js reformats it as needed.
Also add a badge to the README, inspired by <https://github.com/jvm-repo-rebuild/reproducible-central>, …

Build: Avoid non-deterministic timestamp in published builds

---

.travis.yml
Gruntfile.js
README.md
RELEASE.md
build/prep-release.js
build/review-package.js
package.json
rollup.config.js
src/cli/utils.js

* Automate the workflow I have been using for auditing the release artefacts prior to publication. This protects against mistakes or other accidents that may have gone unnnoticed (e.g. in how Rollup is configured, or what files we embed and distribute), as well as against any compromise or other malicious activity in the build chain (in one of the many unaudited dev dependencies we use from npm, or elsewhere).
* No longer recommend `npm run serve`. This can't easily be run in an isolated environment as it needs to expose a port. Unlike other build scripts, this involves unaudited dev dependencies. Recommend use of the built-in and dependency-free HTTP server from Python or PHP instead.
* Minor improvements throughout RELEASE.md, especially to simplify and consolidate related steps, and …

Build: Add audit script for reviewing changes to build artifacts 

---

docs/assert/notPropEqual.md
docs/assert/propEqual.md

Follows-up 9ab52becfdd, in which I made a small last-minute change after having reviewed the diff last, and in that change I caused some copy-paste mistakes behind.

Docs: Fix incomplete propEqual() example

---

lib/global-this-polyfill.js
rollup.config.js
src/export.js
src/globals.js
src/test.js

This fixes #1557 by adopting [globalThis](https://github.com/tc39/proposal-global), and polyfilling it for environments that don't implement it yet via `@ungap/global-this`.

strict mode compatibility

---

test/cli/fixtures/expected/tap-outputs.js
test/cli/helpers/execute.js
test/cli/main.js
test/cli/watch.js

Remove use of regexes and instead strictly compare exact strings, but normalise two things:
* collapse any Node internals into a single frame called "internal".
* strip line/column numbers of our own build artefact.

Tests: Make CLI test cases easier to debug with normalised stack

---

src/html-reporter/html.js

For added robustness, allow the DOM node to be missing at this point just in case.
Extracted from https://github.com/qunitjs/qunit/pull/1391.

HTML Reporter: Check for undefined `testItem` in testDone callback

---

src/html-reporter/html.js

Often when pasting in a filter string, a user may copy extra whitespace, causing QUnit to throw an error about no tests matching.
After looking through the tests, I'm not sure the best place to put a unit test. If the maintainers are interested in adding this functionality, I'll figure out the best place to add the test.

Trim whitespace of filter input

---

src/cli/find-reporter.js
test/cli/fixtures/expected/tap-outputs.js

This is in prep for the js-reporters v2 release, which introduces a third reporter (SummaryReporter) that is for programmatic use only (it has no CLI output).

CLI: Simplify internal find-reporter.js logic for js-reporters

---

test/cli/fixtures/expected/tap-outputs.js
test/cli/helpers/execute.js
test/cli/main.js

Follows-up e295106, which left one test case still using regexes. Upon changing that to use the new normalised tracing, I found that it failed on Node 15 because the format of source map traces changed between Node 14 and Node 15.
This doesn't matter for QUnit in general, since it just prints whatever trace was given to it by the runtime, regardless of formatting, but for our test cases to pass when run against Node 15 we do need to have two test cases or normalise across them. I did the latter.

Tests: Update internal fixture to accomodate Node 15 source map traces

---

package-lock.json
package.json
test/.eslintrc.json
test/autostart.js
test/cli/fixtures/memory-leak/index.js
test/cli/main.js
test/es2018/async-functions.js
test/events.js
test/main/assert/timeout.js
test/main/dump.js
test/main/test.js
test/module-filter.js
test/onerror/outside-test.js
test/reorder.js
test/reporter-html/reporter-html.js
test/reporter-html/unhandled-rejection.js
test/reporter-urlparams-hidepassed.js
test/startError.js

* Migrate from `qunit/two` to `qunit/recommended`.
* Disable various rules that are not so useful for QUnit's internal tests or have unresolved upstream issues that I think make them not yet worthwhile to enable vs noticing those issues ourselves during code review.
https://github.com/platinumazure/eslint-plugin-qunit/blob/v6.0.0/CHANGELOG.md

Build: Update to eslint-plugin-qunit 6

---

package-lock.json
package.json
test/cli/fixtures/expected/tap-outputs.js

Fixes https://github.com/qunitjs/qunit/issues/1340.
Fixes https://github.com/qunitjs/qunit/issues/1406.
Fixes https://github.com/qunitjs/qunit/issues/1555.

CLI: Upgrade `js-reporters` to 2.0.0

---

src/qunit.css

Tweak our colors away from the semi-greyish colors we had before,
toward more dark/saturated or bright colors.
Also reduce the overall number of distinct colors, reusing the same
ones more often.
* Change most uses of black (`#000000`) to `#0D3349`, which is the very dark blue we already used for the `#qunit-header` background.
* Change text in `#qunit .pass` from `#528CE0` to `#2F68DA`, this is more saturated and appears darker. I also moved its hue slightly from cyan-blue, more toward blue-violet.
* Change the text color for `#qunit-testresult` from `#3B81AF` to the same dark blue as used for module names, `#366097`. The color previously used here was a medium blue that we didn't use for any other text.
* Change the Rerun link from the **near-invisible** `#C2CCD1` to instead inherit the …

HTML Reporter: Increase contrast and use richer colors overall

---

src/cli/run.js
test/cli/main.js

Resolves #1593.
The failing unittests for the ESM support lead to repairs in `src/cli/run.js`. I was observing different errors than just the one we were sniffing for, so I added another check with as much granularity as possible. This passes in both coverage and non-coverage runs now.
The other failing unittest was regarding source-maps; here we were simply getting different stack traces based on maps, and from what I could gather, the codecoverage mode was already doing mapping, and then `--enable-source-maps` does more, and seemed to be conflicting. I filtered this test under code coverage mode by inspecting the `NYC_PROCESS_ID` env var. I wanted to use `BUILD_TARGET=coverage`, but that is being set in a different process from what ultimately runs this test.

Fix unittest failures in Node14 under coverage mode

---

src/assert.js
test/cli/fixtures/done-after-timeout.js
test/cli/fixtures/drooling-done.js
test/cli/fixtures/expected/tap-outputs.js
test/cli/fixtures/too-many-done-calls.js
test/cli/main.js
test/main/async.js

This is a more tightly scoped version of #1595, tackling only the `assert.async` callback error handling. The remainder (handling the `onError` and `global failure` scenarios) grew larger than expected, so I'd like to slice this part off for iterative improvements, and circle back on the more generic issues.
The source change is straightforward.
Whenever a "done" callback is fired outside of the originating test, we currently see this:
```
assert.async callback called after test finished.
```
We can tease that apart for 2 distinct use cases.
If we're in another test, we can use `pushFailure` to show:
```
`assert.async` callback from test 'foobar' was called during this test.
```
Or if we're outside of the tests, we can `throw`:
```
`assert.async` callback from test 'foobar' called after …
```

Indicate which test drooling assert.async callbacks came from

---

src/module.js
test/cli/fixtures/only/module.js

Resolves #1610.
The `isParentModuleInQueue` routine wasn't looking at the `ignored` bit on the modules; yes, the parent module is technically in the queue, but it's been filtered and we need to honor that so more modules aren't added into the queue if a prior module used the `only` affordance.
Qualification: Added a small portion into an existing unittest that exercises this fix, and also manually bashed in CLI and browser regarding other "nested" and "flat" scenarios with `only` workflows.

Filter queued modules based on `ignored` bit to handle nested-modules issue

---

src/core/config.js
src/core/processing-queue.js
test/cli/fixtures/assert-expect/no-tests.js
test/cli/fixtures/expected/tap-outputs.js
test/cli/main.js

This PR adds an optional `failOnZeroTests` configuration that defaults to `true`.
Some context:
For apps using `ember exam` throwing errors when no tests are run can cause issues, since there are cases when running a small number of tests in parallel with multiple browsers where some browsers may not get any tests; however, the test-suite as a whole does have tests. In this case, we prefer to only error when there are no tests at all, not in the case where an individual browsers gets no tests.

Core: Add new `failOnZeroTests` configuration option

---

docs/QUnit/test.each.md
src/test.js
test/main/each.js

Follow up on https://github.com/qunitjs/qunit/issues/1568#issuecomment-835627337 to add support for objects as input to `test.each`.
@Krinkle, @smcclure15 let me know what your thoughts are on this change.

Support objects as input to test.each

---

build/prep-release.js

Following up on [this conversation](https://github.com/qunitjs/qunit/pull/1569#discussion_r633010577): replace "unreleased" with the version number in docs when releasing a new version.
```
git diff                                                          
diff --git a/docs/QUnit/test.each.md b/docs/QUnit/test.each.md                            
index 463537b..52e9ce0 100644                                                                                                                                                        
--- a/docs/QUnit/test.each.md                                                                                                                                                        
+++ b/docs/QUnit/test.each.md …
```

Build: Add version release number in unreleased docs

---

src/test.js
test/main/each.js
test/main/test.js

This restores previous behaviour to avoid breaking plugins that might
already extend or monkey-patch QUnit to add additional parameters to
the test callback.
Also:
* Declare the params setting in the Test class for added clarity, and to ensure a consistent object shape.
* Make more use of the new `addTest()` function that was added in https://github.com/qunitjs/qunit/pull/1569, this reduces a lot of duplication. Thanks @ventuno!
While at it, I shifted the abstraction slightly to expose the Test class settings directly, thus making the `addTest()` mainly
be responsible for the queuing and filtering, and no longer responsible for formatting the Test class settings.
With the added use of ES2015 shorthand property name syntax, this feels almost identical using function parameters.

Core: Only pass internal argument to test callback when using each()

---

docs/assert/async.md
docs/assert/timeout.md
docs/config/QUnit.config.md
docs/config/QUnit.extend.md
docs/config/QUnit.push.md
docs/config/QUnit.stack.md
src/core/utilities.js

* Consistently use lowercase for primitive types and `any`.
* Consistently use YAML syntax for `categorie` front matter.
* Consistently order the front matter of config pages.
* Remove `status: deprecated` front matter, which is no longer used (we use categories and version_deprecated instead.)

Docs: Minor improvements to `assert.timeout()` description

---

src/core/on-uncaught-exception.js
test/cli/fixtures/bad-callbacks/begin-throw.js
test/cli/fixtures/bad-callbacks/done-throw.js
test/cli/fixtures/bad-callbacks/moduleDone-throw.js
test/cli/fixtures/bad-callbacks/testStart-throw.js
test/cli/fixtures/expected/tap-outputs.js
test/cli/helpers/execute.js
test/cli/main.js

Capture the status quo before changing it.
Minor changes:
* Switch remaining notEquals/indexOf uses to the preferred `assert.true( str.includes() )` idiom.
* Fix duplicate printing of error message due to V8's `Error#stack`, as used by onUncaughtException.
Ref https://github.com/qunitjs/qunit/pull/1629.
* Start normalizing stderror in tests like we do with stdout.
* Account for qunit.js stack frames from native Promise in V8, which doesn't include a function name or paranthesis.
Ref https://github.com/qunitjs/qunit/issues/1446.
Ref https://github.com/qunitjs/qunit/issues/1633.

Tests: Add tests covering callback failures

---

docs/assert/rejects.md
test/main/assert.js

Added a paragraph and example to the docs showing what is returned from the `assert.rejects` method and when it may be appropriate to leverage it; addresses parts of #1631.
Also backfilled some unittests to verify it returns a `thenable`.

Docs: Details `rejects` return value

---

test/main/assert.js
test/main/deepEqual.js

This has not been needed since the QUnit 2.0 release some years ago,
which raised the minimum support requirement to IE 9+.

Tests: Remove obsolete fallbacks for `Object.create()`

---

docs/assert/async.md

Use the shorter `count` name in the docs, matching the source code.
Correct that this is the number of "calls", not "callbacks".
Remove implication that this marks the test as "done", rather it marks the async pause as done. In phrasing, simply say "resume" instead.
Remove mention of "invoking specified number of times" from the intro sentence since this is rarely used and might be confusing. Bring it up in the later sentences instead.

Docs: Improve explanation of `assert.async()` with count param

---

src/html-reporter/html.js
test/reporter-html/reporter-html.js

Switch from `QUnit.begin()` to `QUnit.done()` to the `runStart` and `runEnd` events, as well as the data these provide, such as the test counts and runtime.
As part of making the interface less cluttered, I propose we remove the runtime and status-specific counts from the real-time progress text, as these were rapidly changing and are hard to read.
These changes, together, would allow removal of a number of things:
* Remove internal dependency on Test class (in favour of runStart data).
* Remove local counting of test by status (in favour of runEnd data).
* Remove local time measuring.
I've moved the progress line from being the third line in the testresult-display element, to be the first line. This way, the number of completed tests will be in the same place as where it is displayed …

HTML Reporter: Internally use `runStart` and `runEnd` events

---

src/assert.js
src/cli/run.js
src/html-reporter/es6-map.js
src/test.js
test/cli/fixtures/drooling-done.js
test/cli/fixtures/drooling-extra-done-outside.js
test/cli/fixtures/drooling-extra-done.js
test/cli/fixtures/expected/tap-outputs.js
test/cli/fixtures/semaphore/nan.js
test/cli/fixtures/semaphore/restart.js
test/cli/main.js
test/main/async.js
test/main/promise.js

When creating two async pauses in a test, it was possible for a test to pass by invoking one of them twice, and the other not at all.
Easy scenario (though perhaps not realistic):
> Use `assert.async()` twice, assigned as done1 and done2 in the same `QUnit.test()` case, and then simulate the failure scenario such that you wrongly call done1 two times, and forget to call done2.
Complex scenario across `QUnit.test()` and "afterEach" hooks, since these previously shared a single semaphore:
> Use `assert.async()` once in a simple test, and schedule the resume call in the future, but then fail with an uncaught error. The uncaught error is found and `Test.run()` would internally kill the pause by resetting the semaphore to zero (this make sense since we shouldn't wait for the release once the …

Assert: Improve detection of bad calls to `assert.async()` callbacks

---

src/module.js
test/cli/cli-main.js
test/cli/fixtures/expected/tap-outputs.js
test/cli/fixtures/module-nested.js

Fixes https://github.com/qunitjs/qunit/issues/1478.

Core: Fix bad module nesting when module closure throws global error

---

src/test.js
test/cli/cli-main.js
test/cli/fixtures/expected/tap-outputs.js
test/cli/fixtures/memory-leak/index.js

Make sure that even if a module is entirely skipped, its hooks are deleted out of the global config so that they don't cause data they reference to leak.
Fixes #1649

Core: ensure skipped modules' hooks don't leak

---

src/html-reporter/html.js

Follows-up 8f5e7ed, which fixed the bug where in the "No tests" error (or indeed any global error after tests are done running) could cause the test runner to get stuck.
That change maintained backward compatibility by continuing to count these global errors as "failed tests", so that CI reporters listening for `QUnit.done()` on `QUnit.on("runEnd")` continue to get the same negative signal. And, it continued to visually render them as a failed test if they happen during test execution or as the last/only event.
But... it inserted the element into the DOM without making visible, which fooled our internal unit tests.
Fix https://github.com/qunitjs/qunit/issues/1651.

HTML Reporter: Fix `display: none` regression on global error message

---

src/core/processing-queue.js
src/html-reporter/html.js
src/test.js
test/cli/fixtures/expected/tap-outputs.js

Historically, the "No tests were run" message was thrown as a real uncaught error by us, recieved by the native error handler in the browser or Node.js, and we then listened to that to generate a failing test case to show in the UI for extra visibility. The use of fake tests in this way wasn't great and caused problems when they happened after a "skip" module, or if there error came from QUnit.begin, runStart, testStart, or beforeEach hooks, since that would prevent the test from coming through and left internals in a broken state.
We fixed that in QUnit 2.17 by rendering uncaught errors directly to the UI instead of queueing them up as a fake test that may or may not make it to the UI.
To preserve API compatibility, we still count this as a failed test and still make it flip "status" to …

Core: Restore fake test for "No tests were run" message

---

src/module.js
test/cli/fixtures/only/module.js

Resolves #1645.
The first time we process a `module.only` call, we chop the list of tests that have accumulated so far, and then mark everything after that as an early-return to not even process it. But there's the edge-case where we're currently within a nested module, which might add more tests as "siblings" to that module.only usage. By forcefully marking the `currentTest` as `ignored`, we are sure to accurately filter other trailing cases.
Added a unittest by squeezing in a new test case to a prior test for `module.only`. That is admittedly growing in complexity, but I think still serves as a great integration-level test to really stress the combinations.

Core: correct flat module.only usage by marking currentModule as ignored

---

docs/QUnit/module.md
docs/QUnit/test.todo.md

Started fixing a typo ("failling").
Then I saw the `this`/arrow functions being mismatched in the example. It still "passes" (as a todo), but maybe cryptically ("wait, it throws because the method isn't implemented, but that... fails, and makes... the todo pass?"). Streamlined those to read like well-formed tests should they start passing.
I had to confirm that `todo` tests pass even with exceptions, and noted that that detail was lacking in the todo-docs.
Wordsmithing welcomed

Doc: Fixing typo and cleaning up code snippets

---

docs/assert/notPropContains.md
docs/assert/notPropEqual.md
docs/assert/propContains.md
docs/assert/propEqual.md
src/assert.js
src/core/utilities.js
test/main/assert.js

I think this is a good addition to the existing QUnit public API. It is rather too common that I need to partially check object values. Also includes `notPropContains`.
Example:
```js
assert.propContains(new User({ id: 1, firstName: 'Izel' }), { firstName: 'Izel' });
assert.notPropContains(new User({ id: 1, firstName: 'Izel' }), { firstName: 'Timo' });
```

assert.propContains API Implementation & Tests

---

docs/QUnit/hooks.md
docs/QUnit/module.md
src/core.js
src/core/config.js
src/core/hooks.js
src/test.js
test/cli/cli-main.js
test/cli/fixtures/expected/tap-outputs.js
test/cli/fixtures/hooks-global-context.js
test/cli/fixtures/hooks-global-order.js

Ref https://github.com/qunitjs/qunit/issues/1475.
-------
Re-created PR due to a GitHub bug not letting me re-open https://github.com/qunitjs/qunit/pull/1670.

Core: Add `QUnit.hooks` to globally add beforeEach and afterEach

---

src/cli/run.js
test/cli/cli-main.js

Fixes https://github.com/qunitjs/qunit/issues/1667.

CLI: Fix ESM file imports on Windows to use file-protocol URLs

---

src/html-reporter/html.js

| Before | After
|--|--
| ![Before: No results for "support for pomise"](https://user-images.githubusercontent.com/156867/162635139-3f3bd458-e322-4479-b5a2-cab8cff22751.png) | ![After: Various results even for "suortprose eachwhit"](https://user-images.githubusercontent.com/156867/162635233-70105acc-114e-4e9b-a9b3-d7d7ffcf68e0.png)
I love the super fast [fuzzysort.js](https://github.com/farzher/fuzzysort) library. Previously we ommitted results with a score lower than `-10000`. fuzzysort does not return results that don't contain the input characters, so names that don't match the input at excluded no matter what. The previous threshold more or less correlated with allowing some letters to be skipped in the first word, and leaving off letters from the end of later words. For example, …

HTML Reporter: Faster and fuzzier module dropdown filter

---

docs/QUnit/module.md
docs/_data/sidebar_api.yml
docs/assert/notPropEqual.md
docs/assert/verifySteps.md
docs/callbacks/QUnit.moduleDone.md
docs/callbacks/QUnit.on.md
docs/callbacks/QUnit.testDone.md
docs/config/hidepassed.md

I found and fixed a few typos in docs :-)

Fixed several typos in docs

---

docs/assert/notPropEqual.md
src/core/config.js
src/html-reporter/html.js
test/cli/helpers/execute.js

There are small typos in:
- docs/assert/notPropEqual.md
- src/core/config.js
- src/html-reporter/html.js
- test/cli/helpers/execute.js
Fixes:
- Should read `property` rather than `propery`.
- Should read `occurs` rather than `ocurrs`.
- Should read `naturally` rather than `naturaly`.
- Should read `insensitive` rather than `insenstive`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

src/core/utilities.js

While reading the source code I realized this internal function isn't needed anymore if we drop the IE support:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes#browser_compatibility

Core: Remove inArray with native array.includes()

---

bin/qunit.js
src/cli/find-reporter.js
src/core/utilities.js
src/html-reporter/html.js
src/reporters.js
src/reporters/PerfReporter.js
src/reports/suite.js
src/reports/test.js
test/cli/PerfReporter.js
test/cli/fixtures/expected/tap-outputs.js

This is in preparation for QUnit 3 where we'd like to make it possible to enable this on Node.js, not just in browsers.
For now it remains unconditionally enabled, and limited to browsers by virtue of using `window.performance`. The reason we don't enable it unconditionally is due to its overhead and that it should remain opt-in for QUnit CLI.
I'm still gathering feedback, but it's possible we'll make it opt-in for browsers as well, depending how significant the overhead is and how often people use this.
Another way might be to leave it on by default when using the HTML reporter, but that when someone configures the list of reporters explicitly (e.g. to enable "TAP" in the browser for a CI pipeline) to then automatically turn off any default reporters ("html" and "perf").
In other words, …

Core: Add `QUnit.reporters.perf` (factor PerfReporter from suite.js)

---

src/assert.js
test/main/async.js

Added type checking for assert.async, so for an invalid input like string, the page would not hang indefinitely.
Fixes [#1721](https://github.com/qunitjs/qunit/issues/1721)

Core: Add type checking for assert.async

---

lib/promise-polyfill.js
test/main/promise.js

The Promise polyfill needed to save the unmodified setImmediate function in IE to use for Promise._immediateFn

Core: Fix compatibility with sinon.useFakeTimers in IE

---

src/test.js
test/cli/cli-main.js
test/cli/fixtures/expected/tap-outputs.js
test/cli/fixtures/pending-async-after-timeout.js

Follows-up 163c9bcf60 (https://github.com/qunitjs/qunit/pull/1642), which changed an internalRecover() to internalStart(), whereas internalStart will (correctly) not resume if there are other pauses still remaining.
Change this back to internalRecover().
Fixes https://github.com/qunitjs/qunit/issues/1705.

Core: Fix hanging `assert.async()` after `assert.timeout()`

---

src/core.js
src/core/config.js
src/core/processing-queue.js
src/test.js

This is motivated by the last remaining build warning from Rollup:
> src/qunit.js → qunit/qunit.js...
> (!) Circular dependency
> src/test.js -> src/core/processing-queue.js -> src/test.js
> created qunit/qunit.js in 2s
ProcessingQueue needs access to the `test` function defined in test.js.
Fix by turning the module into a class, that we create a singleton of in core.js (with access to test.js) and then use that singleton where we previously used ProcessingQueue statically.

Core: Refactor internal ProcessingQueue into class

---

build/prep-release.js
docs/QUnit/load.md
docs/QUnit/start.md
docs/assert/async.md
src/core.js
src/html-reporter/html.js

Based on https://github.com/qunitjs/qunit/pull/1502 by @smcclure15.
Closes https://github.com/qunitjs/qunit/issues/1084.

Core: Deprecate `QUnit.load()` and document migration path

---

package-lock.json
package.json

Update `node-watch` from 0.7.3 to 0.7.4  (latest).
<https://github.com/yuanchuan/node-watch/releases/tag/0.7.4>
<https://github.com/yuanchuan/node-watch/commits/master>
Previously [at https://github.com/qunitjs/qunit/issues/1522.](https://github.com/qunitjs/qunit/issues/1524)

CLI: Upgrade `node-watch` to 0.7.4

---

src/html-reporter/html.js

QUnit 2.21.0:
> 254 tests completed in 912 milliseconds, with 0 failed, 7 skipped, and 4 todo.
> 819 assertions of 823 passed, 4 failed.
New:
> 254 tests completed in 0.9 seconds, with 0 failed, 7 skipped, and 4 todo.
For details, refer to the two sepaerate commit messages.

HTML Reporter: Update testresult display in QUnit 3.0

---

src/html-reporter/html.js

Follows-up https://github.com/qunitjs/qunit/pull/1311.
This fixes a regression in QUnit 2.7.0. Since then, when viewing a finished test run and turning on "Hide passed" and then turning it off again, displays the results in reversed order.
This was because we hide each test from top to bottom (and push into the array), but then upon re-inserting them we used `pop()`, which means we first append the last test to the end of the page, and then the before-last is popped after that and appended to what is now the end of the page, etc. The end result is the tests originally display from A-Z, and are stored in the array from A-Z as well, but then after toggling on/off, get rendered Z-A.

HTML Reporter: Fix reversed order after clicking "Hide passed"

---

test/main/modules.js

Use separate properties to be able to distinguish between own and inherited ones. When "appending" to a property, it effectively copies it do the own object, making it hard to notice whether the properties of a parent module really are copied/preserved at each step, vs only visible at step 1 where it copies it thus masking later bugs where we might forget to extend/mixin the parent env.
Also add a test for the module scope callback's context object.
Ref https://github.com/qunitjs/qunit/pull/1762.

Test: Add more tests for test context in module scope and inheritence

---

src/core/utilities.js
src/module.js
src/test.js
test/main/async.js
test/main/modules.js

The before and after hooks run once per module as long as there is at least one test in the module. Using environment inheritance allows us to use the module context in those hooks, which allows reading the expected changes to the context from a before hook inside nested modules.
This is a breaking change from 2.x behavior. Previously the `after` hook ran with the last test's context instead of the module context, which allowed it to access things set on `this` from inside the test. That will no longer be accessible, and some of the tests were relying on that behavior, so I had to refactor them to get that information from variables in scope for both the test and after hook instead.
This PR replaces #1559
Fixes #1328.
Ref #869.

Core: Run before and after hooks with module context

---

src/reporters/HtmlReporter.js

https://qunitjs.com/api/config/urlConfig/
Demonstrated by <http://localhost:4000/test/reporter-urlparams.html> fixture.
This creates consistency with how we render label/input checkboxes, and improves spacing in the design.
Before (top), After (bottom).

HTML Reporter: Fix `<label>` to wrap `<select>` for multi-value urlConfig item

---

src/core.js
test/main/stacktrace.js

Safari implements ES6 Tail-Call Optimization, which is when:
- the file is in strict mode,
- and, in a regular function (not async or generator),
- and, the return statement ends in a simple function call.
Then, the current function is removed from the stack before the child function begins. TCO applies even for calls that are not recursive.
The result is that, given:
> makeFakeFailure -> exampleMain -> exampleParent -> exampleCurrent ->
> QUnit.stack -> sourceFromStacktrace -> new Error.
In Firefox and Chrome, `e.stack` is:
```
[0] sourceFromStacktrace (SLICED)
[1] QUnit.stack          (SLICED)
[2] exampleCurrent
[3] exampleParent
[4] exampleMain
[5] makeFakeFailure
```
But, in Safari, the second frame gets lost because our tiny `QUnit.stack()` function is a candidate for Tail-Call …

Core: Fix missing second frame in QUnit.stack() in Safari

---

docs/api/QUnit/module.md
docs/api/QUnit/test.each.md
docs/api/QUnit/test.if.md
docs/api/QUnit/test.skip.md
src/module.js
src/test.js
test/cli/fixtures/test-if.js
test/cli/fixtures/test-if.tap.txt
test/main/deepEqual.js
test/main/stacktrace.js
test/main/test.js
test/reorderError1.js
test/reorderError2.js

This builds on previous ideas and discussions from https://github.com/qunitjs/qunit/pull/434 and https://github.com/qunitjs/qunit/issues/637.
-------
It is unacceptable to me for users to have to come up with constructs like the following:
```js
QUnit[supportsFoo ? 'test' : 'skip']('example, function (assert) {
```
Reading the pattern poses a barrier to new developers, because it doesn't look like a method call. We generally write conditional statements in source code as `if (true) { a(); } else { b(); }`. You have to stare at it for a while, and realize that this was likely done to avoid having to duplicate the name and callback, since unlike in normal code, in tests it's kind of the point that name and callback are inlined for idiomatic and ergonomic reasons. This is the closest to …

Core: Add `QUnit.test.if()` and `QUnit.module.if()`

---

docs/browser.md
src/qunit.css
src/reporters/HtmlReporter.js
test/main/HtmlReporter.js

| Before (main) | After
|--|--
| [Live demo: https://codepen.io/Krinkle/full/GRbKpMY](https://codepen.io/Krinkle/full/GRbKpMY) | [Live demo: https://codepen.io/Krinkle/full/JjQPYOy](https://codepen.io/Krinkle/full/JjQPYOy)
| <img width="1349" alt="Screenshot" src="https://github.com/qunitjs/qunit/assets/156867/71f4345f-6eb3-4495-8c15-d3627cfbea45"> | <img width="1349" alt="Screenshot" src="https://github.com/qunitjs/qunit/assets/156867/9bfcf5fa-25b0-45be-b60a-d4c3861b4d52">
| <img width="1365" alt="" src="https://github.com/qunitjs/qunit/assets/156867/386e59d8-b317-40cf-aa7c-532aece84f32"> | <img width="1365" alt="" src="https://github.com/qunitjs/qunit/assets/156867/3e2186ea-97ab-48f2-bd25-4c24d2495061">
This may be a breaking change for themes that rely on the default HTML as created by …

HTML Reporter: QUnit 3.0 theme structure and layout

---

docs/api/assert/expect.md
docs/api/assert/step.md
docs/api/assert/verifySteps.md
src/assert.js
src/test.js
test/cli/fixtures/assert-expect-failure-step.js
test/cli/fixtures/assert-expect-failure-step.tap.txt
test/main/assert-step.js
test/main/modules-es2018.js

This example is now treated as having one assertion rather than three.
```js
QUnit.test('example', function (assert) {
// assert.expect(1);
// Previously:
// assert.expect(3);
assert.step('x');
assert.step('y');
assert.verifySteps(['x', 'y']);
});
```
This better matches the mental model of building up a buffer of values and then comparing them, just like the following would be:
```js
QUnit.test('example', function (assert) {
// assert.expect(1);
var data = [];
data.push('x');
data.push('y');
assert.deepEqual(data, ['x', 'y']);
});
```
In addition to being less surprising to new developers and more intuitive to experienced ones, it also removes the need for busywork in the form of keeping the assertion count up-to-date when merely changing the number of values in the list, before …

Assert: Exclude `assert.step()` calls from `assert.expect()` count

---

src/assert.js
src/core/config.js
src/test.js
test/cli/fixtures/assert-expect-failure-step.js
test/cli/fixtures/assert-expect-failure-step.tap.txt
test/cli/fixtures/assert-expect-step-warning.js
test/cli/fixtures/assert-expect-step-warning.tap.txt
test/main/assert-step.js

Part of the transition plan to offer a smoother path from QUnit 2.x to QUnit 3.0, discussed in https://github.com/qunitjs/qunit/pull/1775.
Ref https://github.com/qunitjs/qunit/issues/1226.
/cc @getify

Assert: Introduce `QUnit.config.countStepsAsOne`

---

docs/api/assert/expect.md
docs/api/config/countStepsAsOne.md

Part of the transition plan to offer a smoother path from QUnit 2.x to QUnit 3.0, discussed in https://github.com/qunitjs/qunit/pull/1775, implemented in https://github.com/qunitjs/qunit/pull/1779, ref https://github.com/qunitjs/qunit/issues/1226.
/cc @getify

Docs: Add migration guide for QUnit.config.countStepsAsOne

---

bin/qunit.js
package-lock.json
package.json

1. ✅ Verify package publication metadata.
2. ✅ Review package diffs.
3. ✅ Repeat the above two steps for any changed or added indirect dependencies: None.
4. ✅ What is this package used for: CLI options parsing.
5. ✅ Test relevant use of package (how, if manually, or covered by CI): Covered by CI.
Previously at https://github.com/qunitjs/qunit/issues/1564:
> ```
> $ npm info commander@7.1.0
>
> commander@7.1.0 | MIT | deps: none
>
> maintainers:
> - zhiyelee <zhiyelee@gmail.com>
> - somekittens <rkoutnik@gmail.com>
> - tjholowaychuk <tj@vision-media.ca>
> - vanesyan <romain.vanesyan@gmail.com>
> - shadowspawn <npm_j@ruru.gen.nz>
> - abetomo <abe@enzou.tokyo>
>
> published 3 weeks ago by abetomo <abe@enzou.tokyo>
> ```
Now:
```
$ npm info commander@12.1.0
commander@12.1.0 | MIT | deps: …
```

CLI: Upgrade `commander` from 7.2 to 12.1.0

---

src/core/reporters/TapReporter.js
src/core/stacktrace.js
test/cli/fixtures/async-module-error-promise.tap.txt
test/cli/fixtures/async-module-error-thenable.tap.txt
test/cli/fixtures/async-module-error.tap.txt

Internal frames are those from qunit.js, or Node.js runtime.
* Remove any internal frames from the top of the stack.
* Grey out later internal frames anywhere in the stack.
This change is applied to the TAP reporter, which the QUnit CLI uses by default. The benefit of trimming initial qunit.js internal frames also benefits use of the TAP reporter in browser environments.
This change inspired by an upcoming change, which converts our fake "No tests" test failure into a normal error. When we emitted it as a fake test, it benefitted from QUnit.stack() trimming qunit.js frames, thus guruanteeing the stack to start at the QUnit.test() call, skipping the first few frames, and anything after the user code is also by definition not of interest.
For generic errors, we weren't doing this yet. And, …

Core: Exclude or grey internal frames from stack traces in TAP reporter

---

demos/grunt-contrib-qunit.js
demos/grunt-contrib-qunit/package.json
src/core/core.js
src/core/processing-queue.js
src/core/reporters/TapReporter.js
src/core/test.js
test/cli/cli-main.js
test/cli/fixtures/async-module-error-promise.tap.txt
test/cli/fixtures/async-module-error-thenable.tap.txt
test/cli/fixtures/async-module-error.tap.txt
test/cli/fixtures/no-tests.tap.txt
test/cli/fixtures/only-test-only-module-mix.js
test/cli/fixtures/only-test-only-module-mix.tap.txt
test/cli/fixtures/syntax-error.tap.txt
test/cli/fixtures/unhandled-rejection.tap.txt
test/main/TapReporter.js

* Remove hacky re-entrance from ProcessingQueue.done() -> test() + advance() -> done(), existed only for this purpose.
This also removes the need for the 99aee51a8a workaround, which avoided a crash by infinite loop.
* Remove unused internal `test` injection to ProcessingQueue, existed only for this purpose.
* Remove "omit stack trace" logic in test.js, existed only for this purpose. To keep output for the "No tests" error similarly clean and distraction-free, the TAP reporter treats error stack traces with a similar cleaner since https://github.com/qunitjs/qunit/pull/1789.
* Remove unused internal `validTest` mechanism existed only for this purpose.
This was originally impossible to trigger externally because it required setting `validTest` to a private symbol. In QUnit 1.16 this was …

Core: Convert "No tests were run." from fake test to error

---

.eslintrc.json
build/tasks/test-on-node.js
src/cli/run.js
src/core/export.js
test/benchmark/micro.js
test/cli/fixtures/inception.js

In QUnit 2.x, we always set the QUnit global in browser contexts, but
outside browsers, we only set the global if CJS/AMD wasn't detected.
Then, in the QUnit CLI, we set the global anyway, and we expect other
test runners to do the same, since that's how most QUnit tests are
written, including for Node.js targets.
In practice, the QUnit global would only be missing in custom test
runners that 1) target Node.js, 2) require/import qunit.js directly,
and 3) don't export it as a global.
I'm aware many communities import 'qunit' directly in each test file
for improved type support. That's great, and avoids needing to rely
on globals. But, that's not a requirement I want to impose on everyone,
especially for simple no-build-step and browser-facing projects.
Improve portability between test …

Core: Always define globalThis.QUnit

---

.eslintrc.json
.gitignore
demos/bundlers.js
demos/bundlers/Gruntfile.js
demos/bundlers/README.md
demos/bundlers/build.mjs
demos/bundlers/package.json
demos/bundlers/test/.eslintrc.json
demos/bundlers/test/import-default.js
demos/bundlers/test/import-indirect.js
demos/bundlers/test/import-named.js
demos/bundlers/test/package.json
demos/bundlers/test/require-default.cjs
demos/bundlers/test/require-indirect.cjs
demos/bundlers/test/src.js
demos/grunt-contrib-qunit.js
demos/karma-qunit.js
demos/nyc.js
demos/testem.js

This is in preparation for adding an ESM distribution to QUnit. Before we do so, let's first observe how and what works today:
* import default: `import QUnit from 'qunit';`
* import named QUnit: `import { QUnit } from 'qunit';`
* import named methods: `import { module, test } from 'qunit';`
* require default: `require('qunit')`
In addition, verify that within a given bundler, a mixture of these across multple files, in indirect ways, always refers to the same object, both functionally (extensions to the object are visible to others), and by object identity (strict equality).
Specifically to satisfy Webpack, I've renamed the fixtures that use `require()` from `.js` to `.cjs` as [Webpack refuses](https://webpack.js.org/api/module-methods/) to compile `require()` calls otherwise in a …

Demos: Add Rollup and Webpack examples

---

demos/bundlers/build.mjs

Follows-up https://github.com/qunitjs/qunit/pull/1787.

Docs: Document non-obvious parts of /demos/bundlers/build.mjs

---

docs/api/assert/pushResult.md
docs/resources/example-fail.html
src/core/on-uncaught-exception.js
src/core/reporters/HtmlReporter.js
src/core/reporters/TapReporter.js
src/core/test.js
test/cli/cli-main.js
test/cli/fixtures/assert-expect-failure-step.tap.txt
test/cli/fixtures/assert-expect-failure.tap.txt
test/cli/fixtures/assert-expect-no-assertions.tap.txt
test/cli/fixtures/async-test-throw.tap.txt
test/cli/fixtures/config-noglobals-add.tap.txt
test/cli/fixtures/config-noglobals-remove.tap.txt
test/cli/fixtures/config-notrycatch-hook-rejection.tap.txt
test/cli/fixtures/config-notrycatch-test-rejection.tap.txt
test/cli/fixtures/config-requireExpects.tap.txt
test/cli/fixtures/config-testTimeout.tap.txt
test/cli/fixtures/done-after-timeout.tap.txt
test/cli/fixtures/drooling-done.tap.txt
test/cli/fixtures/drooling-extra-done.tap.txt
test/cli/fixtures/hanging-test.tap.txt
test/cli/fixtures/hooks-global-throw.tap.txt
test/cli/fixtures/pending-async-after-timeout.tap.txt
test/cli/fixtures/timeout.tap.txt
test/cli/fixtures/too-many-done-calls.tap.txt
test/cli/fixtures/uncaught-error-after-assert-async.tap.txt
test/cli/fixtures/uncaught-error-in-hook.tap.txt
test/cli/fixtures/unhandled-rejection.tap.txt

This was setting `actual: null` and, left expected unset/undefined. In HtmlReporter this idom was recognised to mean "don't show values", based on hasOwn for `expected`. This worked because QUnit.log() passes the internal assert result object as-is.
In TAP output, this was not skipped because Test.js#logAssertion copies the object for the testEnd.errors array, and in doing so forges an `expected` property to exist no matter what, thus with an implied value of undefined. The hasOwn checks in TapReporter thus always evaluate to true.
This meant TAP output for pushFailure() calls not only showed redundant actual/expected entries, but actively created confusion by setting them to different values, drawing attention to a supposed difference that has no meaning
> actual: null
> expected: …

CLI: Remove confusing `expected: undefined` from TAP for non-assert fail

---

src/core/reporters/TapReporter.js
src/core/stacktrace.js
test/cli/cli-main.js
test/cli/fixtures/config-noglobals-add.tap.txt
test/cli/fixtures/config-noglobals-remove.tap.txt
test/cli/fixtures/config-notrycatch-hook-rejection.tap.txt
test/cli/fixtures/config-notrycatch-test-rejection.tap.txt
test/cli/fixtures/config-testTimeout.tap.txt
test/cli/fixtures/done-after-timeout.tap.txt
test/cli/fixtures/hanging-test.tap.txt
test/cli/fixtures/pending-async-after-timeout.tap.txt
test/cli/fixtures/timeout.tap.txt

Follows-up https://github.com/qunitjs/qunit/pull/1789, which applied this to traces under uncaught errors. We now apply this clean up to traces under assertion failures as well.
| Before | After
|--|--
| <img width="490" alt="" src="https://github.com/user-attachments/assets/4b9af7de-731d-4498-a7da-d375bd93ee0d"> | <img width="536" alt="" src="https://github.com/user-attachments/assets/b2b9f830-dad2-43df-8995-864756115b13">
|  <img width="564" alt="" src="https://github.com/user-attachments/assets/303fa612-72a5-46b5-a530-4220ecf9c08a"> | <img width="564" alt="" src="https://github.com/user-attachments/assets/a30bcc81-25f3-4e90-a61c-cc4ef061d11a">

CLI: Apply trace cleaning and internal greying to assertion stack

---

demos/qunit-onerror-early.html
src/core/browser/browser-runner.js
src/core/reporters/HtmlReporter.js
src/core/start.js
test/config-reporters.html

For a long time, we've been quietly recommending in documentation examples to have an HTML structure in which `qunit.js` is loaded at the end of the `<body>`. As of this PR, that now renders the UI immediately instead of waiting for all source code and test suites to load first, which can take a while in large projects. Additionally, if a project has only synchronous tests, the page will remain blank for another whole second (or until all tests have completed running).
Minor changes:
* /demos/qunit-onerror-early.html
Add an "boomBegin" option, to allow separate testing of "normal" early early errors, and errors from QUnit.begin().
* /test/config-reporters.html
Move `<div id=qunit>` up so that we cover code for disabling QUnit.config.reporters after qunit.js. This code previously existed …

HTML Reporter: Add support for early rendering

---

docs/api/QUnit/test.each.md
src/core/test.js
test/cli/fixtures/each-array-labels.js
test/cli/fixtures/each-array-labels.tap.txt
test/cli/fixtures/test-if.tap.txt
test/main/promise.js

Fixes https://github.com/qunitjs/qunit/issues/1733.
```tap
TAP version 13
ok 1 array of strings [0]
ok 2 array of strings [1]
ok 3 array of strings [2]
ok 4 array of strings [3]
ok 13 array of mixed [0]
ok 14 array of mixed [1]
ok 15 array of mixed [2]
ok 16 array of mixed [3]
ok 17 array of mixed [4]
ok 18 array of mixed [5]
ok 19 array of mixed [6]
ok 20 array of mixed [7]
ok 21 array of mixed [8]
ok 22 array of mixed [9]
ok 23 array of mixed [10]
ok 27 keyed objects [caseFoo]
ok 28 keyed objects [caseBar]
```
```tap
TAP version 13
ok 1 array of strings [foo]
ok 2 array of strings [xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx]
ok 3 array of strings [$]
ok 4 array of strings [http://example.org]
ok 13 array of mixed [0: undefined]
ok 14 array of mixed [1: null]
ok 15 array of mixed [2: …
```

Core: Add automatic labels in test.each() for primitive values in arrays

---

bin/qunit.js
docs/api/config/seed.md
src/cli/run.js
src/core/config.js
test/cli/cli-main.js

* Change `--seed` to require a value.
This fixes the conflict with test file arguments, raised in https://github.com/qunitjs/qunit/issues/1691.
* Add `--seed=true` to generate a new seed.
This makes it consistent with URL Params, where `?seed` (which translated to `seed=true`) already did this. With this patch, we now also support pre-config `qunit_config_seed=true` and `qunit_config_seed="true"`. As well as `--seed=true` on the CLI. And URL param `?seed=true` (in case someone tries/expects that). 
While at it, this also:
* Remove duplicate logic from CLI for generating new seed value in value of `/src/core/config.js`, by translating `--seed` to a preconfig.
Fixes https://github.com/qunitjs/qunit/issues/1691.

CLI: Add `--seed=true` to generate a new seed

---

src/core/reporters/TapReporter.js
test/main/TapReporter.js

Don't apply colors to the "ok 1" and "not ok 1" prefix. This has the benefit of making the test names easier to visually extract for developers.
It also increases compatibility with the popular `tap-parser` package which doesn't parse TAP lines correctly otherwise, since blocks like "not ok" must start on a new line, and with the color code in front, they are technically either a continuation of the previous block, or an ignored "Anything" line between two blocks.
This hasn't been a problem in practice, since, if you pipe output from QUnit or TapReporter to a different process that uses tap-parser, colors are naturally disabled. But, if you get the console output from a browser process, the colors will be applied. I caught this while working on QTap (<https://github.com/qunitjs/qtap>). …

CLI: Limit colors in TAP reporter to test names
