- Gruntfile.js
- reporter/html.js
- test/reporter-html-legacy-markup.html
- test/reporter-html-no-qunit-element.html
Creating a PR for @leobalter's branch, to have a proper reference when merging.
Fixes #732
Closes #731
> Fix html reporter toolbar bug

- src/dump.js
This PR was made to double check the CLA
Fixes #750
Closes #751
> Dump: Fix .name/.property doublettes - CLA check

- .travis.yml
Ref: http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade#How-can-I-use-container-based-infrastructure%3F"
> Build: Update Travis-CI config

- src/test.js
- test/main/promise.js
> Test: Don't pass Promise fulfillment value to QUnit.start

- reporter/html.js
- src/core/config.js
Replaces #769 
Fixes #664
@jzaefferer this is rebased and I squashed @gauravmittal1995 commits to clarify the changes I applied after.
> HTML Reporter: Collapse multiple failing tests

- src/test.js
Closes #870
This fixes a regression bug that was preventing the module hooks from
being assigned on the following tests of the same module.
To make it work without reverting the changes on fdf00a4, it improves
the reordered queue for tests that previously failed in the same
browser session.
---
This little bug took me 3 hours to fix, at least the queue is a little bit faster now.
> Test: Fix regression when a failing test canceled the module hooks

- package.json
Closes #900
This might solve the issue reported on #900, but I first need to apply it as a PR to trigger the CI process.
> Build: Update grunt-coveralls to 1.0.0

- Gruntfile.js
- build/tasks/test-on-node.js
- package.json
Ref https://github.com/jquery/qunit/pull/882#issuecomment-163337734
cc @Krinkle
> Improve test-on-node grunt task

- build/tasks/test-on-node.js
- reporter/html.js
- src/assert.js
- src/core.js
- src/core/initialize.js
- src/core/stacktrace.js
- src/core/utilities.js
- src/export.js
- src/test.js
- test/deprecated.js
- test/logs.js
- test/main/assert.js
- QUnit.reset
- QUnit.config.autorun
- Assert#throws
- extra cleanups
Closes #453 
Closes #974 - @gibson042, would you confirm this one, please?
Closes #660 
Closes #604
> More deprecations pre-2.0

- src/equiv.js
- test/main/deepEqual.js
> Core: QUnit.equiv object methods comparison

- reporter/html.js
- src/qunit.css
This adds a stop button that will set the queue length to 0.
This will allow the current test to finish executing,
but then finish the test run.
Fixes gh-928
> HTML Reporter: Add a stop button

- Gruntfile.js
- package.json
- src/globals.js
- test/sandboxed-iframe-contents.html
- test/sandboxed-iframe.html
Do not directly refer to window.sessionStorage (#1090)
> Core: Ability to run in sandboxed iframe, (#1090)

- src/assert.js
This commit should fix error in IE 8-9.
> Fixes #1092

- reporter/html.js
- src/qunit.css
> HTML Reporter: Display todo tests on hidepassed

- README.md
I also moved each badge to its own line for readability (Github-flavored markdown doesn't create line breaks without having 2 trailing spaces on the previous line). Let me know if you have questions/issues.
> Readme: Added Gitter badge

- src/reports/suite.js
- src/reports/test.js
- src/test.js
> Core: Fix test instance memory leak

- src/assert.js
- test/main/async.js
Fixes https://github.com/qunitjs/qunit/issues/1019.
> Assert: Throw if async callback invoked after test finishes

- docs/QUnit/start.md
- docs/config/QUnit.push.md
- docs/css/styles.css
Ref https://kramdown.gettalong.org/syntax.html#html-blocks
Fixes gh-1140
> Docs: Render markdown inside HTML blocks

- src/test.js
- test/callbacks.js
> Tests: Emit `suiteEnd` and trigger `moduleDone` for parent modules

- docs/_layouts/wrapper.html
Fixes https://github.com/qunitjs/qunit/issues/1157.
> Docs: Fix title and index link

- bin/require-qunit.js
- bin/run.js
- package.json
- test/cli/require-qunit-test.js
- yarn.lock
Fixes https://github.com/qunitjs/qunit/issues/1158.
> CLI: Prefer local version of QUnit

- Gruntfile.js
- bin/qunit
A small fix that I noticed while working on other stuff.
> Build: Include bin file in eslint

- src/assert.js
Fixes https://github.com/qunitjs/qunit/issues/1202
> Assert: Fix assert.push deprecation link

- RELEASE.md
> Build: Update release documentation

- src/test.js
- test/main/test.js
Fixes https://github.com/qunitjs/qunit/issues/1213
> Test: Provide descriptive feedback when missing test callback

- bin/run.js
- test/cli/fixtures/syntax-error/test.js
- test/cli/main.js
Fixes https://github.com/qunitjs/qunit/issues/1201.
> CLI: Catch file load failures and report as failing tests

- bin/run.js
- test/cli/fixtures/expected/watch-tap-outputs.js
- test/cli/watch.js
Fixes https://github.com/qunitjs/qunit/issues/1182
> CLI: Clear require cache of watched files between runs

- docs/assert/step.md
- docs/assert/verifySteps.md
Fixes https://github.com/qunitjs/qunitjs.com/issues/131
> Docs: Add further clarification and examples for Step API

- src/test.js
- test/onerror/outside-test.js
Fixes https://github.com/qunitjs/qunit/issues/1166
Still need to determine the best way to add a test for this.
> HTML Reporter: Fix regression in error reporting

- src/assert.js
- test/main/assert/step.js
> Assert: Reset internal steps list after verifySteps

- .eslintrc.json
- reporter/html.js
- src/core/utilities.js
- src/dump.js
- src/test.js
- test/reporter-html/reporter-html.js
I've left `ignoreEOLComments` on to avoid changing the style of those comments.
> All: Enable ESLint no-multi-spaces rule

- docs/assert/verifySteps.md
> Docs: assert.verifySteps() called multiple times.

- test/main/deepEqual.js
- yarn.lock
This should update the version of ESLint used, and thuss expose
the style violation Jenkins caught.
Assuming it does so, I'll update this PR with a fix for the style violation.
Ref https://github.com/qunitjs/qunit/issues/1248.
> Build: Update yarn.lock

- docs/assert/step.md
- src/assert.js
- test/main/assert/step.js
Ref: https://github.com/qunitjs/qunit/pull/1261#issuecomment-364330296
> Fail test when passing a non string value to assert.step

- .eslintrc.json
- bin/find-reporter.js
- bin/run.js
- reporter/html.js
- test/cli/fixtures/npm-reporter/index.js
- test/main/assert/timeout.js
- test/main/deepEqual.js
- test/reporter-html/reporter-html.js
- test/reporter-html/single-testid.js
- test/reporter-html/window-onerror-preexisting-handler.html
- test/reporter-html/window-onerror-preexisting-handler.js
This fixes some minor lint issues.
> All: Enable ESLint recommended rules

- .travis.yml
Node.js 4 & 9 are ending their life
> Tests: Stop testing on Node 4 & 9

- src/core.js
- src/module.js
As requested in https://github.com/qunitjs/qunit/pull/1168#discussion_r117645535
> Core: Extract QUnit.module to its own file

- test/reporter-html/no-qunit-element.html
> fix HTTP 404 error for the Qunit CSS in one of the test files

- package.json
- yarn.lock
* modernized code-base (node 6+)
* no other changes
> CLI: Sane Bump

- Gruntfile.js
- build/coverage-bridge.js
- package-lock.json
- package.json
- test/sandboxed-iframe-contents.html
- yarn.lock
> Build: Upgrade grunt-contrib-qunit to 3.x (Headless Chrome)

- Gruntfile.js
> Build: Avoid Chromium sandbox on Jenkins (as for Travis CI)

- test/cli/fixtures/expected/tap-outputs.js
- test/cli/fixtures/fail/throws-match.js
- test/cli/main.js
Ref https://github.com/qunitjs/qunit/issues/1333.
> Tests: Add case for assert.throws() matching

- package.json
> Build: Update engine requirement package.json to Node 6

- RELEASE.md
Some updates from my following the document for 2.9.0.
> Docs: Add a few missing steps to release docs

- docs/assert/deepEqual.md
Via comments on
https://gerrit.wikimedia.org/r/#/c/mediawiki/extensions/Popups/+/488977/1//COMMIT_MSG@10.
> Doc: deepEqual() checks strict inherited equality

- test/cli/require-qunit-test.js
Fixed minor typo from `installled` to `installed`.
> Tests: Fixed minor typo in the test

- src/test.js
We have a very large test suite (11K tests) and I noticed that a lot of time was spent generating stack traces when defining the tests on loading the page. This PR still captures the source of the stack trace, but defers generating the stack trace itself until we need it.
For our test suite, this reduced the time spent in the `QUnit.test` function by about 2 seconds, which makes a big difference to the developer feedback loop.
> Core: Defer getting the test source until we need it

- reporter/html.js
Sample implementation for "Step 1" of the Recommended implementation https://github.com/qunitjs/qunit/issues/1438.
> WIP HTML Reporter: Change how the list of modules is rendered and filtered

- .travis.yml
We're on <https://gitter.im/qunitjs/> nowadays.
> Build: Remove irc notifications

- bin/qunit.js
- docs/_layouts/home.html
- src/core/processing-queue.js
- src/dump.js
* <https://qunitjs.com/>
* <https://excamera.com/sphinx/article-xorshift.html>
* <https://flesler.blogspot.com/2008/05/jsdump-pretty-dump-of-any-javascript.html>
> Docs: Use HTTPS for urls that support it

- docs/_config.yml
This one is registered to the jQuery Infrastructure team.
Ref https://github.com/qunitjs/qunitjs.com/commit/d8d068fecee3950de8b9181991b8a9336d620364.
>  Search: Switch to new Algolia account

- test/.eslintrc.json
- test/cli/fixtures/expected/tap-outputs.js
- test/cli/fixtures/sourcemap/source.js
- test/cli/fixtures/sourcemap/source.min.js
- test/cli/fixtures/sourcemap/source.min.js.map
- test/cli/helpers/execute.js
- test/cli/main.js
Ref https://github.com/qunitjs/qunit/issues/590.
> Tests: Confirm that NODE_OPTIONS --enable-source-maps works

- docs/assert/equal.md
- docs/assert/false.md
- docs/assert/notOk.md
- docs/assert/ok.md
- docs/assert/true.md
Doesn't appear relevant or helpful.
> Docs: Remove mention of JUnit from some assert method descriptions

- Gruntfile.js
- build/tasks/test-on-node.js
_Depends on: https://github.com/qunitjs/qunit/pull/1515_
-------
Ref #1511.
>  Build: Rewrite test-on-node task to use QUnit.on()

- docs/index.md
Ref https://github.com/qunitjs/qunit/pull/1532
> Docs: Add /category/all/ legacy redirect

- package-lock.json
- package.json
Closes https://github.com/qunitjs/qunit/issues/1524.
> Build: Upgrade `node-watch` to 0.7.1

- .editorconfig
- .eslintrc.json
- .travis.yml
- lib/promise-polyfill.js
- package.json
- src/export.js
- src/logger.js
- src/promise.js
- test/main/assert.js
- test/mozjs.js
Fixes https://github.com/qunitjs/qunit/issues/1535.
> Core: Repair support for SpiderMonkey runtime 

- History.md
Closes https://github.com/qunitjs/qunit/issues/1547.
> Docs: Fix bad issue reference in 2.14 change log

- package-lock.json
- package.json
Closes https://github.com/qunitjs/qunit/issues/1546.
> CLI: Upgrade `commander` to 2.6.1

- RELEASE.md
- build/dist-replace.js
- rollup.config.js
- src/qunit.css
Follows-up 6ea16c7 and https://github.com/qunitjs/qunit/issues/1538.
> Build: Get rid of "Date" from release builds entirely

- bin/qunit.js
- package-lock.json
- package.json
Closes https://github.com/qunitjs/qunit/issues/1564.
> CLI: Upgrade `commander` to 7.1.0

- test/reporter-html/diff.js
> Polyfill String.repeat for IE test runs

- src/module.js
- test/cli/fixtures/async-module-warning/promise-test.js
- test/cli/fixtures/async-module-warning/test.js
- test/cli/fixtures/expected/tap-outputs.js
- test/cli/main.js
> Core: Warn when a module callback has a promise as a return value

- docs/config/QUnit.config.md
Ref https://github.com/qunitjs/qunit/pull/1617.
/cc @brendenpalmer
> Docs: Write documentation for new `QUnit.config.failOnZeroTests` option

- Gruntfile.js
- test/index.html
- test/mozjs.js
Ref https://github.com/qunitjs/qunit/pull/1569.
Ref https://github.com/qunitjs/qunit/issues/1511.
> Tests: Run each.js tests in test-on-node and mozjs.js too

- build/watch.js
When Rollup finds an error (e.g. syntax error typo in a source file), it provides an Error object with added properties. Some of these are quite large (e.g. watchedFiles), or otherwise less useful. Format the error object into a string, similar to what Rollup normally does.
When Rollup finds an error during the first run, the error is thrown from the manual Rollup API call - before the watcher exists, and thus it causes three problems:
1. the error is reported by Node.js as an unhandled rejection,
2. the watcher won't get created,
3. the process won't exit (given active http server).
Address the first issue by attaching a `catch()` handler.
Address the third issue by explicitly exiting the process if we encounter a generic script error before the watcher is created.
The second issue …
> Build: Improve error handling in `build:dev` script

- build/watch.js
Use node-watch to listen for src/qunit.css, and copy it over with the same preprocess() applied as Rollup and Grunt.
Adjust log messages to differentiate between `[rollup]` and `[css]`.
Remove seemingly redundant `process.on("exit")` listener for cleaning up the watchers since this is afaik only when terminating the process manually which happens just fine (and quietly) with and without this.
Closes https://github.com/qunitjs/qunit/issues/1581.
> Build: Add copying of CSS to "build:dev" task

- src/module.js
- test/cli/cli-main.js
- test/cli/fixtures/expected/tap-outputs.js
- test/cli/fixtures/only/module-then-test.js
- test/cli/fixtures/only/module.js
Ref https://github.com/qunitjs/qunit/issues/1645.
Ref https://github.com/qunitjs/qunit/pull/1658.
> Tests: Add "only/module-then-test.js" test fixture

- src/qunit.css
Implemented recommendation from CSS Validator
> Disallow units for 0 values in qunit.css

- test/index.html
- test/main/modules.js
This should make it significantly more robust and easier to see what's actually going on, primarily to help review https://github.com/qunitjs/qunit/pull/1762.
> Test: Refactor module hook/context state testing

- docs/_data/projects.yml
* https://github.com/SAP/openui5
* https://ui5.sap.com/#/topic/09d145cd86ee4f8e9d08715f1b364c51
* https://en.wikipedia.org/wiki/SAP
* https://en.wikipedia.org/wiki/OpenUI5
> Docs: Add SAP OpenUI5 to Projects
